### PR TITLE
httpx: update to 0.16.1

### PR DESCRIPTION
**Pull request by OriginCode**
Topic Description
-----------------

Update `httpx` and its dependencies.

Package(s) Affected
-------------------

- httpx
- sniffio
- httpcore
- hstspreload

Security Update?
----------------

- [ ] Yes
- [x] No

Architectural Progress
----------------------

- [x] Architecture-independent `noarch`

### CODE REVIEW

**Review by MingcongBai — APPROVED** [review]

**Comment by MingcongBai** [comment]
Please revert the removal of `hstspreload`, while it used to be a dependency for `httpx`, it is not a task for this topic to remove packages that is "no longer needed."

**Comment by OriginCode** [comment]
Test example:
```python
# Run with `python3`
import httpx
r = httpx.get('https://example.org')
print('Status Code: ', r.status_code)
print('Content-type: ', r.headers['content-type'])
print('Content: ', r.text)
```

With asyncio:
```python
import httpx
import asyncio
async def main():
    async with httpx.AsyncClient() as client:
        r = await client.get('https://example.org/')
    print('(async) Status Code: ', r.status_code)
    print('(async) Content-type: ', r.headers['content-type'])
    print('(async) Content: ', r.text)

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

My result:
image
image

**Comment by MingcongBai** [comment]
@OriginCode All working as expected! Merging.

**Comment by MingcongBai** [comment]
Post-Merge Architectural Progress
----------------------




- [x] Architecture-independent `noarch`

**Pull request merged**
