### PR TITLE
udiskie: update to 2.5.3

### PR DESCRIPTION
**Pull request by BC204**
Topic Description
-----------------

- udiskie: install manpage and license
- udiskie: update to 2.5.3

Package(s) Affected
-------------------

- udiskie: 2.5.3

Security Update?
----------------

No

Build Order
-----------

```
#buildit udiskie
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] Architecture-independent `noarch`

### CODE REVIEW

**Comment by MingcongBai** [comment]
Why update PKGBREAK?

**Comment by BC204** [comment]
> Why update PKGBREAK?

There is a commit to add a manpage for udiskie that has not yet been submitted.

**Comment by BC204** [comment]
> Why update PKGBREAK?

Removed unnecessary update.

**Comment by jiegec** [comment]
Missing /usr/bin/udiskie?

**Comment by BC204** [comment]
> Missing /usr/bin/udiskie?

Fixed.

**Comment by MingcongBai** [comment]
@BC204 Still missing icons.

**Comment by BC204** [comment]
> @BC204 Still missing icons.

The upstream changed the path of icons.
截图 2024-08-22 10-15-44
截图 2024-08-22 10-05-35
截图 2024-08-22 10-05-49

**Comment by MingcongBai** [comment]
> > @BC204 Still missing icons.
> 
> The upstream changed the path of icons. 截图 2024-08-22 10-15-44 截图 2024-08-22 10-05-35 截图 2024-08-22 10-05-49

I see.

**Review by MingcongBai — APPROVED** [review]
Tested good on AMD64.

**Pull request merged**
