### PR TITLE
steam: update to 1.0.0.81

### PR DESCRIPTION
**Pull request by MingcongBai**
Topic Description
-----------------

- steam: update to 1.0.0.81
    Co-authored-by: 白铭骢 (Mingcong Bai) (@MingcongBai) <jeffbai@aosc.io>

Package(s) Affected
-------------------

- steam: 1.0.0.81

Security Update?
----------------

No

Build Order
-----------

```
#buildit steam
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`

### CODE REVIEW

**Comment by MingcongBai** [comment]
Superseded by 1.0.0.82. Closing.

**Comment by MingcongBai** [comment]
Woah - never mind... 1.0.0.81 is still the newest.

**Comment by Icenowy** [comment]
When running postinst, `udevadm hwdb is deprecated. Use systemd-hwdb instead.` appears.

**Comment by Icenowy** [comment]
图片

It works (TM)

**Review by Icenowy — APPROVED** [review]

**Pull request merged**
