### PR TITLE
grc: new, 1.11.3

### PR DESCRIPTION
**Pull request by RedL0tus**
Repo: https://github.com/garabik/grc

Requested by @LionNatsu .

### CODE REVIEW

**Comment by LionNatsu** [comment]
喵

**Comment by MingcongBai** [comment]
@RedL0tus Could you please mark `ABHOST=noarch` if it is not an ELF programme?

**Comment by RedL0tus** [comment]
@MingcongBai Done.

**Comment by MingcongBai** [comment]
Thanks.

**Pull request merged**
