### PR TITLE
mangohud: update to 0.6.1

### PR DESCRIPTION
**Pull request by eatradish**
Topic Description
-----------------

Update MangoHUD to 0.6.1, split `+32` component, enable NVCtrl (monitoring and SMI functions) for NVIDIA GPUs.

- Use upstream source tarball.
- Mark `vulkan*+32` and `glslang+32` as `noarch`.
- Install NVCtrl headers in `nvidia` and `nvidia+32`.

Package(s) Affected
-------------------

- `mangohud`, `mangohud+32` v0.6.1
- `glslang+32` v7.11.3214-1
- `vulkan-loader+32`, `vulkan-tools+32` v1.2.154-1
- `vulkan+32` v0-1
- `nvidia`, `nvidia+32` v455.38-1

Security Update?
----------------

No

Build Order
-----------

```
nvidia
mangohud
glslang+32
vulkan-loader+32
vulkan-tools+32
vulkan+32
nvidia+32
mangohud+32
```

Architectural Progress
----------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
- [x] 32-bit Optional Environment `optenv32`

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
- [x] 32-bit Optional Environment `optenv32`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

### CODE REVIEW

**Review by MingcongBai — APPROVED** [review]
Please just make sure if it still builds - I wasn't sure why we used Git source before.

**Comment by MingcongBai** [comment]
> Should we make a dedicated mangohud+32 package? (In case that someone run x86_32 programs on non-amd64 machines)

I second this, this could be useful with box86. @eatradish All you have to do is to move the `beyond` script under a new `extra-optenv32/mangohud+32` package.

**Comment by eatradish** [comment]
Vulkan+32 too old, wait.

**Comment by MingcongBai** [comment]
MangoHUD split, enabled NVCtrl support.

@eatradish @cthbleachbit Test pending.

**Comment by cthbleachbit** [comment]
2020-12-12 22-33-58屏幕截图

2020-12-12 22-34-59 的屏幕截图

 I assume this means mangohud is working correctly for 64bit GL / Vulkan programs.

**Comment by cthbleachbit** [comment]
`/opt/32/lib/mangohud/libMangoHud.so` is not 32bit x86 ELF file.

```
cth451@cth-desktop-dorm [ mangohud ] ! readelf --header libMangoHud.so 
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x8bd0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          1394504 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         10
  Size of section headers:           64 (bytes)
  Number of section headers:         28
  Section header string table index: 27
```

**Comment by cthbleachbit** [comment]
For the current status, mangohud does not work on 32bit vulkan applications.

**Comment by cthbleachbit** [comment]
It  works now.

**Pull request merged**
