### PR TITLE
linux-kernel-lts: update to 6.6.47

### PR DESCRIPTION
**Pull request by KexyBiscuit**
Topic Description
-----------------

- linux+kernel+lts: update to 6.6.47
- linux-kernel-lts: update to 6.6.47

Package(s) Affected
-------------------

- linux+kernel+lts: 2:6.6.47
- linux-kernel-lts-6.6.47: 6.6.47

Security Update?
----------------

No

Build Order
-----------

```
#buildit linux-kernel-lts linux+kernel+lts
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 and Armv8-A Hyper-V VMs. Note that `modprobe.blacklist=hyperv_fb` is still required for video.

image
image

**Comment by shankerwangmiao** [comment]
`sys_fstat` and `sys_newfstatat` is added back since 6.6.47, la_ow_syscall should be upgraded accordingly, using the version  https://github.com/AOSC-Dev/la_ow_syscall/commits/for-6.11/. But I have not created a release yet, due to lack of testing.

**Comment by OriginCode** [comment]
LGTM on loongarch64:
Screenshot_20240828_021411

**Review by OriginCode — APPROVED** [review]

**Comment by lunzima** [comment]
My generation 1.0 Hyper-V guest cannot start Xorg without loading hyperv_fb. hyperv_drm created /dev/fb0 but Xorg seems to refuse using it.

**Comment by KexyBiscuit** [comment]
> My generation 1.0 Hyper-V guest cannot start Xorg without loading hyperv_fb. hyperv_drm created /dev/fb0 but Xorg seems to refuse using it.

@lunzima Could you please open a separate issue for this, thanks!

**Pull request merged**
