### PR TITLE
Administrative Tools (admin-base) Survey 20221201

### PR DESCRIPTION
**Pull request by MingcongBai**
Topic Description
-----------------

This topic surveys updates from top-level dependencies in `admin-base`, updating where applicable and fixing packages with poor scripting practices.

Package(s) Affected
-------------------

- [x] `acpid` v2.0.34
- [x] `apt-file` v3.3
- [x] `apt` v2.5.4
- [x] `btrfs-progs` v6.0.2
- [x] `cryptsetup` v2.6.0
- [x] `dbus` v1.14.4
- [x] `debianutils` v5.7
- [x] `dosfstools` v4.2-1
- [x] `e2fsprogs` v1.46.5
- [x] `f2fs-tools` v1.15.0
- [x] `fcron` v3.3.0-1
- [x] `fuse` v2.9.9
- [x] `gnupg` v2.3.8
- [x] `gptfdisk` v1.0.9
- [x] `mdadm` v4.2
- [x] `mtd-utils` v2.1.5
- [x] `multipath-tools` v0.9.3
- [x] `nvme-cli` v2.2.1
- [x] `os-prober` v1.81
- [x] `parted` v3.5
- [x] `polkit` v122
- [x] `powerpc-utils` v1.3.10
- [x] `powertop` v2.15
- [x] `pstate-frequency` v3.11.0-1
- [x] `quota-tools` v4.09
- [x] `rfkill` v1.0
- [x] `rpcsvc-proto` v1.4.2-2
- [x] `sg3-utils` v1.47r915
- [x] `shadow` v4.13
- [x] `smartmontools` v7.3
- [x] `sudo` v1.9.12p1
- [x] `sysfsutils` v2.1.1
- [x] `tlp` v1.5.0
- [x] `trousers` v0.3.15
- [x] `xfsprogs` v6.0.0
- [x] `pinentry` 1.0.0-8

Security Update?
----------------

No

Build Order
-----------

```
apt e2fsprogs btrfs-progs cryptsetup dbus debianutils dosfstools f2fs-tools fcron fuse pinentry gnupg gptfdisk os-prober parted polkit rfkill shadow smartmontools sysfsutils trousers xfsprogs sudo mdadm multipath-tools mtd-utils nvme-cli rpcsvc-proto quota-tools sg3-utils powertop apt-file acpid tlp pstate-frequency powerpc-utils
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by Cyanoxygen** [comment]
Testing 
------

Here are the test results for this survey. Each program is manually run.

**Comment by Cyanoxygen** [comment]
### apt 
Apt ran successfully and presented a deprecation warning about Apt Key.
image
image

**Comment by Cyanoxygen** [comment]
### btrfs-progs
Here we have various programs which manipulates btrfs:
image
image
image

**Comment by Cyanoxygen** [comment]
cryptsetup
-------

image

image

**Comment by Cyanoxygen** [comment]
debianutils 
--------
image

dosfstools 
--------
image
image

**Comment by Cyanoxygen** [comment]
e2fsprogs
--------
mkfs.ext4 raised an error, due to incomplete mke2fs.conf:

image

tune2fs, e2fsck works fine:
image

**Comment by Cyanoxygen** [comment]
f2fs-tools
--------
f2fs-tools works fine:
image
image
image
image

**Comment by MingcongBai** [comment]
@Cyanoxygen Kotlin...

**Comment by Cyanoxygen** [comment]
fcron
--------
fcron works fine:
image

P.S. We might need to ship a patched config file that points sendmail to a stub like /bin/true, or add postfix as a dependency (which is broken because invoking sendmail might? spam dozens of lines in the journal)

**Comment by Cyanoxygen** [comment]
fuse
--------
fuse works fine (at least for ntfs-3g):
image

**Comment by Cyanoxygen** [comment]
gnupg
--------
There is no binary executable named `gpg`:
image
instead, `gpg2` is present. Its bash completion is broken due to the nonexistent command `gpg`.

image

**Comment by Cyanoxygen** [comment]
gptfdisk
--------
gptfdisk works fine:
image
and sgdisk:
image

**Comment by Cyanoxygen** [comment]
os-prober parted
--------
Both works fine.
image

**Comment by Cyanoxygen** [comment]
polkit
------
Works fine, at least for systemd:
image

rfkill
--------
Works fine, but this is a VM so it does not have wireless capability.
image

shadow
--------
Works fine.
image
image

**Comment by Cyanoxygen** [comment]
smartmontools
--------
Works fine. It has nothing to do with this VM hard disk though...
image

sysfstools
--------
Works fine.
image

trousers - Fail
--------
tcsd won't start because of invalid permission for /etc/tcsd.conf:
image

**Comment by Cyanoxygen** [comment]
xfsprogs
--------
Works fine:
image
image
image
image

sudo
--------
Works fine:
image

bcache-tools
--------
image

mdadm
--------
Works fine (it's easy to add hard disks to a VM):
image
image
image

**Comment by Cyanoxygen** [comment]
multipath-tools
--------
Works fine (it may not function properly in VM):
image

mtd-utils
--------
It runs (sadly there's no way to add a MTD device to VM):
image

nvme-cli
--------
image

**Comment by Cyanoxygen** [comment]
quota-tools
--------
Works fine (with XFS):
image
image

**Comment by Cyanoxygen** [comment]
sg3-utils
--------
It runs (there is no SATA/SCSI hard disk installed in my laptop, sorry):
image

genfstab
--------
Works fine:
image

kernel-tools:
Works fine:
image

exfat-utils
--------
Works fine:
image
image

**Comment by Cyanoxygen** [comment]
gpart
--------
Works fine:
image
image

jfsutils:
Works fine:
image

reiserfsprogs
--------
Works fine:
image
And this guy requires me to type "Yes" to continue:
image

**Comment by Cyanoxygen** [comment]
hfsprogs
--------
Works fine:
image

hddtemp
--------
It runs (no hard disk installed on my laptop):
image

powertop
--------
Works fine, including tuning:
image
image

**Comment by Cyanoxygen** [comment]
apt-file
--------
Works fine:
image

atm
--------
Works fine:
image

**Comment by Cyanoxygen** [comment]
apt
--------
Manuals of APT suite are good:
image

And APT no longer complains about the deprecated apt-key signature management. Public keys generated by p-vetcor can be directly added to `trusted.gpg.d`.
image

**Comment by OriginCode** [comment]
`/usr/bin/gpg` not found.
圖片

**Comment by Cyanoxygen** [comment]
This topic will be rebuilt with Core 10. Some of the packages in other topics were having trouble building with Glibc 2.36 (because of `sys/mount.h` conflict).

**Comment by Cyanoxygen** [comment]
Package fixes pending
--------
Here is the list of packages needed to be fixed:
- [x] e2fsprogs (broken mkfs.ext4)
- [x] trousers (config file permission issue)
- [x] gnupg (missing gpg command, broken pinentry)

**Comment by Cyanoxygen** [comment]
gnupg - Failed
--------
GnuPG is not able to generate keys due to broken `pinentry`:
image
image

After installing gtk-2, gpg now works normally:
image
image

**Comment by Cyanoxygen** [comment]
e2fsprogs
--------
Now it can create ext4 filesystem:
image
image
image

**Comment by Cyanoxygen** [comment]
pcsd
--------
It does not complain about permission issue now:
image

But TrouSerS does not support TPM 2.0, so it will fail with TPM 2.0 chip.

**Comment by OriginCode** [comment]
gnupg smart card failed to be detected.
圖片

**Comment by OriginCode** [comment]
> gnupg smart card failed to be detected. 圖片

Update: seems to be an issue on my end, resolved after restarting `gpg-agent`

**Comment by Cyanoxygen** [comment]
> > gnupg smart card failed to be detected. 圖片
> 
> Update: seems to be an issue on my end, resolved after restarting `gpg-agent`

Please also make sure `pcscd` is running.

**Review by Cyanoxygen — APPROVED** [review]

**Pull request merged**
