### PR TITLE
[b43-firmware-installer] NEW

### PR DESCRIPTION
**Pull request by liushuyu**
Firmware installer for Broadcom 43XX wireless cards

### CODE REVIEW

**Comment by MingcongBai** [comment]
Several issues.

- Use no `REL` unless building a revision.
- /usr/lib/firmware not /lib/firmware.
- Consider a postrm to remove installed firmware.
- Capitalize first letter for `PKGDES` (trivial).

**Comment by liushuyu** [comment]
Will package manager remove the content of the folder if the folder was empty when installing that package when Uninstall the package ?

**Comment by MingcongBai** [comment]
No. Some other packages may provide contents in it. For instance, `firmware-nonfree`.

**Comment by liushuyu** [comment]
Well, in this case, I will choose to take action later 😃

**Comment by liushuyu** [comment]
BTW,  can ABBS deal with no source URL spec file?

**Comment by MingcongBai** [comment]
You can't. It probably is against licensing agreement to leave such files without user's consent.

**Comment by MingcongBai** [comment]
Use `DUMMYSRC=1`.

**Comment by liushuyu** [comment]
I will sleep now to fix my broken  mind

**Comment by liushuyu** [comment]
Sorry for the accidentally uploaded commits... Let me reopen a new one...

**Pull request closed without merging**
