### PR TITLE
GNOME: Update to 40.0

### PR DESCRIPTION
**Pull request by MingcongBai**
Topic Description
-----------------

Update GNOME to 40.0.

This includes updates to GNOME dependencies, runtime libraries, components, and applications. Versioning may vary, ~just GNOME being GNOME, nothing to see here~.

Several packages, as usual, have not yet released their final versions:

- ~`adwaita-icon-theme` v40\~rc~
- ~`devhelp` v40\~alpha~
- ~`geary` v40\~rc, [reported upstream](https://discourse.gnome.org/t/final-40-0-tag-not-available/6118)~
- ~`gnome-backgrounds` v40\~rc~
- ~`gnome-session` v40\~beta~
- ~`seahorse` v40\~alpha~

**Do not merge this pull request until the aforementioned packages have released their final v40 versions.**

Package(s) Affected
-------------------

See `groups/gnome-40`.

### Other Notable Changes Introduced in this Topic

- Add `gnome-remote-desktop` to `gnome-base`.
- Dropped orphaned `gtk3-nocsd`, `gtk-vector-screenshot`.
- Rename `vte-gtk3` to `vte`, anticipating `vte-gtk4` to be shipped under the same name; transitionalised `vte-gtk3` to depend on `vte`.
- Ship both shared and static libraries with `glslang`, a prerequisite for `gtk-4`.
- Split `libgudev` from `systemd`, as it is long overdue.
- Split `xwayland` from `xorg-server` due to upstream maintenance changes.
- `gst-plugins-bad-1-0` now contains `gst-transcoder`, transitionalising the latter.
- `gtk-update-icon-cache` is now provided via `gtk-4`.

Security Update?
----------------

Yes, #2922 .

Build Order
-----------

Use `groups/gnome-40`.

Architectural Progress
----------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

### CODE REVIEW

**Comment by MingcongBai** [comment]
Pwease GNOME, tag fiwal rewease QAQ

**Comment by MingcongBai** [comment]
Arc Theme, our default theme, does not yet support GNOME 40. Merge inhibited.

**Comment by MingcongBai** [comment]
Seahorse just tagged `40.0`. Woohoo, five to go...

**Comment by MingcongBai** [comment]
The `libdc1394` update in this topic introduced a sover change.

**Comment by MingcongBai** [comment]
"You can continue to ship Geary 3.38 until a 40 release is available, or you could ship the 40.alpha version. Your choice." Geary maintainer also noted a lack of time due to other commitments. Downgrading Geary to 3.38 and calling it a day, for now.

**Comment by MingcongBai** [comment]
Or not (to downgrade Geary).

image

**Review by cthbleachbit — APPROVED** [review]

**Pull request merged**
