### PR TITLE
musicbox: new, 0.2.3.2 & BeautifulSoup4: fix python3 error

### PR DESCRIPTION
**Pull request by LER0ever**
CLI Version of Netease CloudMusic

### CODE REVIEW

**Comment by MingcongBai** [comment]
Which version of Python is this package using? Could you mark `NOPYTHON2=yes` or `NOPYTHON3=yes`?

**Comment by LER0ever** [comment]
Is it still necessary if the package runs under both python 2 and 3?

**Comment by MingcongBai** [comment]
> Is it still necessary if the package runs under both python 2 and 3?

You see, this is an application, but not Python modules... So, yes, for the sake of rigor, specify one, if you know that it works on Python 3, then I would think you should choose 3 for this.

So add `NOPYTHON2=yes` to the `defines`.

**Comment by MingcongBai** [comment]
Just had a conversation with @LER0ever, seems like our `beautifulsoup4` is not working properly for Py3. Waiting on his next PR to fix this issue first.

**Pull request merged**
