### PR TITLE
linux-kernel-lts: update to 6.6.57

### PR DESCRIPTION
**Pull request by KexyBiscuit**
Topic Description
-----------------

- linux-kernel-lts: update to 6.6.57
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.6.57, current HEAD is 8b7d02c78ba0027220959340b644e34d6d2b1b33.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel-lts: Revert "rcu: Fix rcu_barrier() VS post CPUHP_TEARDOWN_CPU invocation"
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.6.57-rc2, current HEAD is 245ec224e51dd4e6b0e9d7ecd7dd743b1b06773c.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel-lts: update to 6.6.57-rc2
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.6.57-rc2, current HEAD is e6efc17783bd18d1356f3325a46d5781e77d7878.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel-lts: update config for 6.6.57-rc1
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux+kernel+lts: update to 6.6.57
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel-lts: update to 6.6.57-rc1
    - Routine patch due diligence for upstream releases.
    - Now following contribution guidelines of Android common kernels <https://android.googlesource.com/kernel/common/+/refs/heads/android-mainline/README.md>.
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.6.57-rc1, current HEAD is 0190e967624488a2681a280eb99ef7fa58d67e35.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>

Package(s) Affected
-------------------

- linux+kernel+lts: 2:6.6.57
- linux-kernel-lts-${__VER}: 6.6.57-1

Security Update?
----------------

No

Build Order
-----------

```
#buildit linux-kernel-lts linux+kernel+lts
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 generation 2, AMD64 generation 1 and Armv8-A generation 2 Hyper-V VMs.

image
image
image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 VMware VM.

- Product: VMware® Workstation 17 Pro
- Version: 17.6.1 build-24319023
- Host OS version: Windows 11 Enterprise, 64-bit (Build 27723.1000) 10.0.27723
- Accelerate 3D graphics: on
- Firmware type: UEFI
- Host VBS Mode: on

image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on 战神Z8-KP7S2 with Optimus on.
Smoke testing passed on 战神Z8-KP7S2 with NVIDIA GPU only and NVIDIA DRM KMS enabled.

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on RedmiBook 16 (锐龙版).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Surface Pro (5th Gen).

Screenshot_20241016_145301

**Comment by KexyBiscuit** [comment]
Smoke testing passed on ROG Ally (2023).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Latitude D630.

image_2024-10-16_15-43-18

**Review by OriginCode — APPROVED** [review]

**Pull request merged**
