### PR TITLE
dynamorio: new, 10.0.0

### PR DESCRIPTION
**Pull request by jiegec**
Topic Description
-----------------

- dynamorio: new, 10.0.0

Package(s) Affected
-------------------

- dynamorio: 10.0.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit dynamorio
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`

### CODE REVIEW

**Comment by MingcongBai** [comment]
This package seems not to have provided any executable files, not sure how to test...

**Comment by jiegec** [comment]
> This package seems not to have provided any executable files, not sure how to test...

`/usr/share/dynamorio/bin64/drrun -c /usr/share/dynamorio/samples/bin64/libcbr.so -- ls`

**Comment by MingcongBai** [comment]
> /usr/share/dynamorio/bin64/drrun -c /usr/share/dynamorio/samples/bin64/libcbr.so -- ls

Hmm, lots of warnings but the command did seem to run:

图片

**Comment by jiegec** [comment]
> > /usr/share/dynamorio/bin64/drrun -c /usr/share/dynamorio/samples/bin64/libcbr.so -- ls
> 
> Hmm, lots of warnings but the command did seem to run:
> 
> 图片

Because we deliberately skipped building 32 bit support.

**Comment by MingcongBai** [comment]
> > > /usr/share/dynamorio/bin64/drrun -c /usr/share/dynamorio/samples/bin64/libcbr.so -- ls
> > 
> > 
> > Hmm, lots of warnings but the command did seem to run:
> > 图片
> 
> Because we deliberately skipped building 32 bit support.

Got it.

**Review by MingcongBai — APPROVED** [review]

**Pull request merged**
