### PR TITLE
linux-kernel: update to 5.9.8

### PR DESCRIPTION
**Pull request by MingcongBai**
Topic Description
-----------------

Update Linux Kernel to 5.9.8.

- Migrate Linux Kernel configuration for AMD64, AArch64 to 5.9.
- Create Linux Kernel configuration for Loongson 3, POWER (`ppc64el`).
- Drop UniVT in favour of KMSCON, as recent `fbcon` earthquake breaks the promise of continued maintenance.
- General driver and feature enablements.
- Enable Kprobes and tracers.
- Update VirtualBox to 6.1.14.

Package(s) Affected
-------------------

- `linux-kernel` v5.9.8
- `linux+kernel` v5.9.8
- `kernel-tools` v5.9.8
- `virtualbox` v6.1.14

Security Update?
----------------

No

Build Order
-----------

`linux-kernel` => `linux+kernel` => `kernel-tools` => `virtualbox`

Architectural Progress
----------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

~- Loongson 3 `loongson3`~
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

~- Loongson 3 `loongson3`~
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

### CODE REVIEW

**Comment by Fearyncess** [comment]
图片
VirtualBox 6.1.14 works well with linux kernel 5.9.8.

**Review by Icenowy — APPROVED** [review]
Approved for a{md,rm}64.
Cannot review for ppc64el.

**Comment by zhmars** [comment]
Hi, the univt patch seems interesting. I think I unstandard why it is abandoned due to recent kernel changes, which is a bit regretful. Anyway, I'm trying to port it to latest stable kernel. If anyone still is interested, you can download it from [this repo](https://github.com/zhmars/Linux-TTY-UTF-8-Patch).

**Comment by MingcongBai** [comment]
@zhmars Thanks for the heads up, we will keep this in mind. However, since the `fbcon` Kernel driver is still undergoing major rework, we will stick to UniVT for now to minimise user intervention.

**Pull request merged**
