### PR TITLE
PowerShell Survey 20241012

### PR DESCRIPTION
**Pull request by KexyBiscuit**
Topic Description
-----------------

- powershell: polish build scripts
- powershell: allow known security vulnerabilities to fix building
- powershell: refactor build scripts

Package(s) Affected
-------------------

- powershell: 7.4.5-1

Security Update?
----------------

No

Build Order
-----------

```
#buildit powershell
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`

### CODE REVIEW

**Comment by KexyBiscuit** [comment]
https://github.com/PowerShell/PowerShell/issues/24418

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64.

```shell
kexybiscuit@ProArtB550-CREATOR [ ~ ] $ pwsh
PowerShell 7.4.5-0-gae3f180145a288e93406dc48454501fe32d29a84
PS /home/kexybiscuit> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5-0-gae3f180145a288e93406dc48454501fe32d29a84
OS                             AOSC OS (11.6.0)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /home/kexybiscuit>
```

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64.

```shell
kexybiscuit@ProArtB550-CREATOR [ ~ ] $ pwsh
PowerShell 7.4.5
PS /home/kexybiscuit> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             AOSC OS (11.6.0)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /home/kexybiscuit>
```

**Comment by MingcongBai** [comment]
Why would we need to disable checks for security vulnerabilities?

**Comment by KexyBiscuit** [comment]
> Why would we need to disable checks for security vulnerabilities?

Comment added.

**Review by MingcongBai — APPROVED** [review]

**Pull request merged**
