### PR TITLE
KDE Survey (March 2024)

### PR DESCRIPTION
**Pull request by MingcongBai**
Topic Description
-----------------

Update key KDE components:

- KDE Frameworks 5.115.0
- KDE Plasma Desktop 5.27.11
- KDE Applications 23.08.5 (with the exception of Spectacle, which was held at 22.12 to avoid usability issues)
- Bump dependencies and rebuild as needed.

Package(s) Affected
-------------------

- akonadi-calendar-tools: 23.08.5
- akonadi-calendar: 23.08.5
- akonadi-contacts: 23.08.5
- akonadi-import-wizard: 23.08.5
- akonadi-mime: 23.08.5
- akonadi-notes: 23.08.5
- akonadi-search: 23.08.5
- akonadi: 23.08.5
- akonadiconsole: 23.08.5
- akregator: 23.08.5
- alligator: 23.08.5
- analitza: 23.08.5
- angelfish: 23.08.5
- arianna: 23.08.5
- ark: 23.08.5
- artikulate: 23.08.5
- attica5: 5.115.0
- audiocd-kio: 23.08.5
- audiotube: 23.08.5
- baloo-widgets: 23.08.5
- baloo: 5.115.0
- blinken: 23.08.5
- bluedevil: 5.27.11
- bluez-qt: 5.115.0
- bomber: 23.08.5
- bovo: 23.08.5
- breeze-grub: 5.27.11
- breeze-gtk: 5.27.11
- breeze-icons: 5.115.0
- breeze-plymouth: 5.27.11
- breeze: 5.27.11
- calendarsupport: 23.08.5
- calindori: 23.08.5
- cantor: 23.08.5
- cervisia: 23.08.5
- cmark: 0.30.3-1
- colord-kde: 23.08.5
- digikam: 7.9.0-3
- discover: 5.27.11
- dolphin-plugins: 23.08.5
- dolphin: 23.08.5
- dragon: 23.08.5
- drkonqi: 5.27.11
- elisa: 23.08.5
- eventviews: 23.08.5
- extra-cmake-modules: 5.115.0
- falkon: 23.08.5
- ffmpegthumbs: 23.08.5
- filelight: 23.08.5
- frameworkintegration: 5.115.0
- futuresql: 0.1.1
- ghostwriter: 23.08.5
- granatier: 23.08.5
- grantlee-editor: 23.08.5
- grantlee5: 5.3.1
- grantleetheme: 23.08.5
- gwenview: 23.08.5
- incidenceeditor: 23.08.5
- itinerary: 23.08.5
- juk: 23.08.5
- k3b: 23.08.5
- kaccounts-integration: 23.08.5
- kaccounts-providers: 23.08.5
- kactivities-stats: 5.115.0
- kactivities: 5.115.0
- kactivitymanagerd: 5.27.11
- kaddressbook: 23.08.5
- kajongg: 23.08.5
- kalarm: 23.08.5
- kalendar: 1:0
- kalgebra: 23.08.5
- kalk: 23.08.5
- kalzium: 23.08.5
- kamera: 23.08.5
- kamoso: 23.08.5
- kanagram: 23.08.5
- kapidox: 5.115.0
- kapman: 23.08.5
- kapptemplate: 23.08.5
- karchive: 5.115.0
- kasts: 23.08.5
- kate-runtime: 23.08.5
- kate: 23.08.5
- katomic: 23.08.5
- kauth: 5.115.0
- kblackbox: 23.08.5
- kblocks: 23.08.5
- kbookmarks: 5.115.0
- kbounce: 23.08.5
- kbreakout: 23.08.5
- kbruch: 23.08.5
- kcachegrind: 23.08.5
- kcalc: 23.08.5
- kcalendarcore: 1:5.115.0
- kcalutils: 23.08.5
- kcharselect: 23.08.5
- kclock: 23.08.5
- kcmutils: 5.115.0
- kcodecs: 5.115.0
- kcolorchooser: 23.08.5
- kcompletion: 5.115.0
- kconfig: 5.115.0
- kconfigwidgets: 5.115.0
- kcontacts: 1:5.115.0
- kcoreaddons: 5.115.0
- kcrash: 5.115.0
- kcron: 23.08.5
- kdav: 1:5.115.0
- kdbusaddons: 5.115.0
- kde-cli-tools: 5.27.11
- kde-dev-scripts: 23.08.5
- kde-dev-utils: 23.08.5
- kde-gtk-config: 5.27.11
- kde-inotify-survey: 23.08.5
- kdebugsettings: 23.08.5
- kdeclarative: 5.115.0
- kdeconnect: 23.08.5
- kdecoration: 5.27.11
- kded: 5.115.0
- kdeedu-data: 23.08.5
- kdegraphics-mobipocket: 23.08.5
- kdegraphics-thumbnailers: 23.08.5
- kdelibs4support: 5.115.0
- kdenetwork-filesharing: 23.08.5
- kdenlive: 23.08.5
- kdepim-addons: 23.08.5
- kdepim-runtime: 23.08.5
- kdeplasma-addons: 5.27.11
- kdesignerplugin: 5.115.0
- kdesu: 5.115.0
- kdev-python: 23.08.5
- kdev-python: 23.08.5
- kdevelop: 23.08.5
- kdewebkit: 5.115.0
- kdf: 23.08.5
- kdialog: 23.08.5
- kdiamond: 23.08.5
- kdnssd: 5.115.0
- kdoctools: 5.115.0
- keditbookmarks: 23.08.5
- kemoticons: 5.115.0
- keysmith: 23.08.5
- kfilemetadata: 5.115.0
- kfind: 23.08.5
- kfloppy: 23.04.3
- kfourinline: 23.08.5
- kgamma: 1:5.27.11
- kgeography: 23.08.5
- kget: 23.08.5
- kglobalaccel: 5.115.0
- kgoldrunner: 23.08.5
- kgpg: 23.08.5
- kguiaddons: 5.115.0
- khangman: 23.08.5
- khelpcenter: 23.08.5
- kholidays: 1:5.115.0
- khotkeys: 5.27.11
- khtml: 5.115.0
- ki18n: 5.115.0
- kiconthemes: 5.115.0
- kidentitymanagement: 23.08.5
- kidletime: 5.115.0
- kig: 23.08.5
- kigo: 23.08.5
- killbots: 23.08.5
- kimageformats: 5.115.0
- kimagemapeditor: 23.08.5
- kimap: 23.08.5
- kinfocenter: 5.27.11
- kinit: 5.115.0
- kio-admin: 23.08.5
- kio-extras: 23.08.5
- kio-gdrive: 23.08.5
- kio-zeroconf: 23.08.5
- kio: 5.115.0
- kipi-plugins: 23.08.5
- kirigami-addons: 0.11.0
- kirigami-gallery: 23.08.5
- kirigami2: 5.115.0
- kiriki: 23.08.5
- kitemmodels: 5.115.0
- kitemviews: 5.115.0
- kiten: 23.08.5
- kitinerary: 23.08.5
- kjobwidgets: 5.115.0
- kjournald: 23.08.5
- kjs: 5.115.0
- kjsembed: 5.115.0
- kjumpingcube: 23.08.5
- kldap: 23.08.5
- kleopatra: 23.08.5
- klettres: 23.08.5
- klickety: 23.08.5
- klines: 23.08.5
- kmag: 23.08.5
- kmahjongg: 23.08.5
- kmail-account-wizard: 23.08.5
- kmail: 23.08.5
- kmailtransport: 23.08.5
- kmbox: 23.08.5
- kmediaplayer: 5.115.0
- kmenuedit: 5.27.11
- kmime: 23.08.5
- kmines: 23.08.5
- kmix: 23.08.5
- kmousetool: 23.08.5
- kmouth: 23.08.5
- kmplot: 23.08.5
- knavalbattle: 23.08.5
- knetwalk: 23.08.5
- knewstuff: 5.115.0
- knights: 23.08.5
- knotes: 23.08.5
- knotifications: 5.115.0
- knotifyconfig: 5.115.0
- koko: 23.08.5
- kolf: 23.08.5
- kollision: 23.08.5
- kolourpaint: 23.08.5
- kompare: 23.08.5
- kongress: 23.08.5
- konqueror: 23.08.5
- konquest: 23.08.5
- konsole: 23.08.5
- kontact: 23.08.5
- kontactinterface: 23.08.5
- kontrast: 23.08.5
- konversation: 23.08.5
- kopeninghours: 23.08.5
- kopete: 23.08.5
- korganizer: 23.08.5
- kosmindoormap: 23.08.5
- kpackage: 5.115.0
- kparts: 5.115.0
- kpat: 23.08.5
- kpeople: 5.115.0
- kpimtextedit: 23.08.5
- kpipewire: 5.27.11
- kpkpass: 23.08.5
- kplotting: 5.115.0
- kpmcore: 23.08.5
- kpty: 5.115.0
- kpublictransport: 23.08.5
- kqtquickcharts: 23.08.5
- kquickcharts: 5.115.0
- krdc: 23.08.5
- krecorder: 23.08.5
- kreversi: 23.08.5
- krfb: 23.08.5
- kross: 5.115.0
- kruler: 23.08.5
- krunner: 5.115.0
- ksanecore: 23.08.5
- kscreen: 5.27.11
- kscreenlocker: 5.27.11
- kservice: 5.115.0
- kshisen: 23.08.5
- ksirk: 23.08.5
- ksmtp: 23.08.5
- ksnakeduel: 23.08.5
- kspaceduel: 23.08.5
- ksquares: 23.08.5
- ksshaskpass: 5.27.11
- ksudoku: 23.08.5
- ksystemlog: 23.08.5
- ksystemstats: 5.27.11
- kteatime: 23.08.5
- ktextaddons: 1.5.3
- ktexteditor: 5.115.0
- ktextwidgets: 5.115.0
- ktimer: 23.08.5
- ktnef: 23.08.5
- ktorrent: 23.08.5
- ktouch: 23.08.5
- ktrip: 23.08.5
- ktuberling: 23.08.5
- kturtle: 23.08.5
- kubrick: 23.08.5
- kunitconversion: 5.115.0
- kwallet-pam: 5.27.11
- kwallet: 5.115.0
- kwalletmanager: 23.08.5
- kwave: 23.08.5
- kwayland-integration: 5.27.11
- kwayland: 5.115.0
- kweather: 23.08.5
- kweathercore: 0.7
- kwidgetsaddons: 5.115.0
- kwin: 5.27.11
- kwindowsystem: 5.115.0
- kwordquiz: 23.08.5
- kwrite: 23.08.5
- kwrited: 5.27.11
- kxmlgui: 5.115.0
- kxmlrpcclient: 5.115.0
- layer-shell-qt: 5.27.11
- libgravatar: 23.08.5
- libkcddb: 23.08.5
- libkcompactdisc: 23.08.5
- libkdcraw: 23.08.5
- libkdegames: 23.08.5
- libkdepim: 23.08.5
- libkeduvocdocument: 23.08.5
- libkexiv2: 23.08.5
- libkgapi: 23.08.5
- libkipi: 23.08.5
- libkleo: 23.08.5
- libkmahjongg: 23.08.5
- libkomparediff2: 23.08.5
- libksane: 23.08.5
- libkscreen: 5.27.11
- libksieve: 23.08.5
- libksysguard: 5.27.11
- libktorrent: 1:23.08.5
- libquotient: 0.8.1.2
- lokalize: 23.08.5
- lskat: 23.08.5
- mailcommon: 23.08.5
- mailimporter: 23.08.5
- marble-runtime: 23.08.5
- marble: 23.08.5
- markdownpart: 23.08.5
- mbox-importer: 23.08.5
- merkuro: 23.08.5
- messagelib: 23.08.5
- milou: 5.27.11
- minuet: 23.08.5
- mlt: 7.22.0
- modemmanager-qt: 5.115.0
- neochat: 23.08.5
- networkmanager-qt: 5.115.0
- okular: 23.08.5
- oxygen-icons: 1:5.115.0
- oxygen: 5.27.11
- palapeli: 23.08.5
- parley: 23.08.5
- partitionmanager: 23.08.5
- picmi: 23.08.5
- pim-data-exporter: 23.08.5
- pim-sieve-editor: 23.08.5
- pimcommon: 23.08.5
- plasma-browser-integration: 5.27.11
- plasma-desktop: 5.27.11
- plasma-disks: 5.27.11
- plasma-firewall: 5.27.11
- plasma-framework: 5.115.0
- plasma-integration: 5.27.11
- plasma-nano: 5.27.11
- plasma-nm: 5.27.11
- plasma-pa: 5.27.11
- plasma-sdk: 5.27.11
- plasma-systemmonitor: 5.27.11
- plasma-thunderbolt: 5.27.11
- plasma-vault: 5.27.11
- plasma-wayland-protocols: 1.10.0
- plasma-welcome: 5.27.11
- plasma-workspace-wallpapers: 5.27.11
- plasma-workspace: 5.27.11
- plasmatube: 23.08.5
- plymouth-kcm: 5.27.11
- polkit-kde-agent-1: 5.27.11
- powerdevil: 5.27.11
- poxml: 23.08.5
- print-manager: 23.08.5
- prison5: 1:5.115.0
- purpose: 5.115.0
- qcoro: 0.10.0
- qmlkonsole: 23.08.5
- qqc2-desktop-style: 5.115.0
- rocs: 23.08.5
- sddm-kcm: 5.27.11
- signon-kwallet-extension: 23.08.5
- skanlite: 23.08.5
- skanpage: 23.08.5
- solid: 5.115.0
- sonnet: 5.115.0
- spectacle: 22.12.3
- step: 23.08.5
- svgpart: 23.08.5
- sweeper: 23.08.5
- syndication: 1:5.115.0
- syntax-highlighting: 5.115.0
- systemsettings: 5.27.11
- telly-skout: 23.08.5
- threadweaver: 5.115.0
- tokodon: 23.08.5
- umbrello: 23.08.5
- xdg-desktop-portal-kde: 5.27.11
- yakuake: 23.08.5
- zanshin: 23.08.5

Security Update?
----------------

No

Build Order
-----------

```
#buildit groups/kf5 groups/plasma qcoro grantlee5 cmark mlt libquotient futuresql ktextaddons kirigami-addons kweathercore groups/kde-applications digikam
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

### CODE REVIEW

**Comment by MingcongBai** [comment]
Manually building this survey, as network connectivity frequently caused build errors.

**Comment by Cyanoxygen** [comment]
digiKam can not start:
```
error while loading shared libraries: libKF5AkonadiContact.so.5: cannot open shared object file: No such file or directory
```

image

**Comment by Cyanoxygen** [comment]
kamoso SIGSEGVs on gstreamer:
image

**Comment by Cyanoxygen** [comment]
image
Discover can not be launched.

**Review by Cyanoxygen — APPROVED** [review]

**Pull request merged**
