### PR TITLE
snapper: new, 0.8.14

### PR DESCRIPTION
**Pull request by OriginCode**
Topic Description
-----------------

Add `snapper`! The ultimate tool for automatically managing your btrfs snapshots!

Package(s) Affected
-------------------

Security Update?
----------------

No

Architectural Progress
----------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

### CODE REVIEW

**Comment by OriginCode** [comment]
image

**Comment by MingcongBai** [comment]
@OriginCode So I take it that it doesn't work yet?

**Comment by OriginCode** [comment]
> @OriginCode So I take it that it doesn't work yet?

Yes, still working on it.

**Comment by OriginCode** [comment]
Latest commit has fixed the issue.

image

**Review by MingcongBai — APPROVED** [review]

**Comment by MingcongBai** [comment]
@OriginCode Would you mind building for other architectures?

**Review by szclsya — APPROVED** [review]

**Pull request merged**
