### PR TITLE
linux-kernel-lts: update to 6.6.53

### PR DESCRIPTION
**Pull request by KexyBiscuit**
Topic Description
-----------------

- linux-kernel-lts: update to 6.6.53
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.6.53, current HEAD is 1b5809db18c01e41aa1806eea21f3fdc20965122.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel-lts: update to 6.6.53-rc1
    - Remove references of MIPS64 Release 6.
    - RC markers are not necessary for this package, removing.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel-lts: update to 6.6.53-rc1
    - Routine patch due diligence for stable releases.
    - Now following contribution guidelines of Android common kernels <https://android.googlesource.com/kernel/common/+/refs/heads/android-mainline/README.md>.
    - Update patch from kernel_compiler_patch.
    - Update lis3 patch from Fedora.
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.6.53-rc1, current HEAD is b9b766174380fa22f0ca5b9c95508e42528ae8fc.
    - Remove references of MIPS64 Release 6.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>

Package(s) Affected
-------------------

- linux+kernel+lts: 2:6.6.53
- linux-kernel-lts-${__VER}: 6.6.53-1

Security Update?
----------------

No

Build Order
-----------

```
#buildit linux-kernel-lts linux+kernel+lts
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 generation 2, AMD64 generation 1 and Armv8-A generation 2 Hyper-V VMs.

image
image
image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 VMware VM.

- Product: VMware® Workstation 17 Pro
- Version: 17.6.0 build-24238078
- Host OS version: Windows 11 Enterprise, 64-bit (Build 27695.1000) 10.0.27695
- Accelerate 3D graphics: on
- Firmware type: UEFI
- Host VBS Mode: on

image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on 战神Z8-KP7S2.

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on RedmiBook 16 (锐龙版).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Surface Pro (5th Gen).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on ROG Ally (2023).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on ProArt B550-CREATOR.

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Latitude D630.

图片

**Comment by MingcongBai** [comment]
Smoke test passed on LoongArch (THTF Chaorui L860-T2, 3A5000M).

**Review by MingcongBai — APPROVED** [review]

**Pull request merged**
