### PR TITLE
grub: improve default user experience

### PR DESCRIPTION
**Pull request by MingcongBai**
Topic Description
-----------------

- grub: improve default user experience
    - Use black-on-white for highlighted selection to improve contrast.
    - Enable GRUB_SAVEDEFAULT to remember the last booted system.
    - Lower the default resolution to 1024x768, making GRUB readable on most
    systems (especially those with HiDPI displays).
    - Disable right-arrow-key-to-select by default to avoid confusion.
    - Use --force-extra-removable for quirk systems.
    - Improve comments for most documentations.
    - Disable graphical terminal for MacBook6,2 as it fails to display.
    - Update Unifont to 16.0.01.

Package(s) Affected
-------------------

- grub: 2:2.12+unifont16.0.01

Security Update?
----------------

No

Build Order
-----------

```
#buildit grub
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 generation 2 Hyper-V VM.

image
image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 generation 1 Hyper-V VM.

image
image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 VMware VM.

- Product: VMware® Workstation 17 Pro
- Version: 17.6.1 build-24319023
- Host OS version: Windows 11 Enterprise, 64-bit (Build 27749.1000) 10.0.27749
- Accelerate 3D graphics: on
- Firmware type: UEFI
- Host VBS Mode: on

image
image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Armv8-A generation 2 Hyper-V VM.

image
image

**Comment by Cyanoxygen** [comment]
Testing
--------

I have chosen to preserve the previous GRUB config file, thus the menu color theme change is not reflected here.

The translated "UEFI Firmware Settings" menu entry is shown below:

image

**Comment by MingcongBai** [comment]
Tested good on LoongArch:

- Loongson XA61200 + AMD Radeon WX 3100
- THTF Chaorui T860-G2 + AMD Radeon R7 240

Both displayed the GRUB menu at 1024x768, as expected. "UEFI Firmware Settings" entry is also localised properly.

**Review by eatradish — APPROVED** [review]

**Comment by eatradish** [comment]
photo_2024-11-17_01-04-51

LGTM

**Comment by KexyBiscuit** [comment]
Smoke testing passed on XA612A0, using on-board HDMI as firmware video output. The resolution is at 1920x1080, maintaining great usability.

**Pull request merged**
