### PR TITLE
Bobcao3 dev

### PR DESCRIPTION
**Pull request by bobcao3**
GLFW update to 3.2.1
GLEW update to 2.0.0
- rebuilds reverse dependencies

### CODE REVIEW

**Comment by MingcongBai** [comment]
And... There is a huge merge commit.

**Comment by MingcongBai** [comment]
It's either a squash or a cherrypick at this point.

**Comment by bobcao3** [comment]
There isn't a package depended on glfw.
However there is a ton on glew...
( I checked these by apt-cache rdepends glew, though  it would be done better by abbs-meta)

**Comment by MingcongBai** [comment]
If you could clean up your PR it would be a whole lot easier...

**Comment by MingcongBai** [comment]
Done, with several cherry-picks. Remember, I will not merge any PRs with no regard to the main branch like this next time.

**Comment by MingcongBai** [comment]
... But thanks for the effort anyways.

**Pull request closed without merging**
