### PR TITLE
ppp: update to 2.4.9

### PR DESCRIPTION
**Pull request by MingcongBai**
Topic Description
-----------------

Update `ppp` to v2.4.9, sync patch set with Fedora.

Package(s) Affected
-------------------

- `ppp` v2.4.9

Security Update?
----------------

No

Architectural Progress
----------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

### CODE REVIEW

**Comment by Neustradamus** [comment]
Any news about this PR?

**Comment by MingcongBai** [comment]
> Any news about this PR?

I'm on it now.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/AOSC-Dev/aosc-os-abbs/issues/2298

**Review by cthbleachbit — APPROVED** [review]

**Comment by Neustradamus** [comment]
@cthbleachbit and @MingcongBai: Thanks! :)

**Comment by Neustradamus** [comment]
@cthbleachbit and @MingcongBai: #2298 can be closed?
This PR fixes the CVE.

**Pull request merged**
