### PR TITLE
vscode: Update to 1.30.1

### PR DESCRIPTION
**Pull request by eatradish**
***This autobuild have some problem, do not merge it***

### CODE REVIEW

**Comment by MingcongBai** [comment]
@eatradish What exactly do you mean by "some problem"?

**Comment by eatradish** [comment]
@MingcongBai The autobuild file cannot be compiled successfully and needs to be further improved.

**Comment by liushuyu** [comment]
What is the issue exactly?

**Comment by eatradish** [comment]
make vscode need nodejs >=8 and < 9

**Comment by liushuyu** [comment]
Superseded by 93b1f0a44aab5d9ac88ac482c7ef38c1a5317957

**Pull request closed without merging**
