### PR TITLE
linux-kernel: update to 6.11.4

### PR DESCRIPTION
**Pull request by KexyBiscuit**
Topic Description
-----------------

- kernel-tools: update to 6.11.4
    - Synchronize patches from linux-kernel.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel: update to 6.11.4
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.11.4, current HEAD is eb4160d8f4c3b6437d3dd75bb8d05516bfa0bc41.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- kernel-tools: synchronize patches from linux-kernel
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel: Revert "rcu: Fix rcu_barrier() VS post CPUHP_TEARDOWN_CPU invocation"
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.11.4-rc2, current HEAD is 9c80d53928728840c25f99771f908f1e53017063.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel: update config for 6.11.4-rc2
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- kernel-tools: update to 6.11.4-rc2
    - Synchronize patches from linux-kernel.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux+kernel: update to 6.11.4
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel: update to 6.11.4-rc2
    - Routine patch due diligence for upstream releases.
    - Now following contribution guidelines of Android common kernels <https://android.googlesource.com/kernel/common/+/refs/heads/android-mainline/README.md>.
    - Update Loongson PWM patches.
    - Update Xe patch for LoongArch.
    - Revert "cpufreq: amd-pstate: initialize core precision boost state".
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.11.4-rc2, current HEAD is 58083fb4a72189c66c07dd2948d388f2382a253e.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel: unset `CONFIG_USB_ONBOARD_DEV` to fix boot livekit on MacBook Pro Mid 2010
- kernel-tools: update to 6.11.3
    - Synchronize patches from linux-kernel.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>

... and 42 more commits

Package(s) Affected
-------------------

- kernel-tools: 6.11.4-1
- linux+kernel: 3:6.11.4
- linux-kernel-${__VER}: 1:6.11.4-1

Security Update?
----------------

No

Build Order
-----------

```
#buildit linux-kernel linux+kernel kernel-tools
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by KexyBiscuit** [comment]
Smoke testing passed for https://github.com/AOSC-Dev/aosc-os-abbs/pull/7680/commits/e1042eda33a55ed5d126571367f1ee56e9bef5f3 on AMD64 Hyper-V VM.

image

**Comment by KexyBiscuit** [comment]
Smoke testing passed for AMD64 and Armv8-A, running on generation 2 virtual machines in Hyper-V.
image
image

**Comment by KexyBiscuit** [comment]
FTBFS on Power ISA (ppc64el), same error as [[linux-next:master /3069] ERROR: modpost: "tpm2_sessions_init" [drivers/char/tpm/tpm_ibmvtpm.ko] undefined!](https://lore.kernel.org/all/202408051735.ZJkAPQ3b-lkp@intel.com/).

**Comment by KexyBiscuit** [comment]
FTBFS on 64-bit LoongArch.

```
  LD      .tmp_vmlinux1
ld: drivers/irqchip/irq-loongarch-avec.o: in function `.LANCHOR3':
irq-loongarch-avec.c:(.data.rel.ro+0x8): undefined reference to `msi_lib_irq_domain_select'
ld: drivers/irqchip/irq-loongson-pch-msi.o: in function `.LANCHOR0':
irq-loongson-pch-msi.c:(.data.rel+0x120): undefined reference to `msi_lib_init_dev_msi_info'
ld: drivers/irqchip/irq-loongson-pch-msi.o: in function `.LANCHOR3':
irq-loongson-pch-msi.c:(.data.rel.ro+0x8): undefined reference to `msi_lib_irq_domain_select'
make[2]: *** [scripts/Makefile.vmlinux:34: vmlinux] Error 1
```

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 generation 2, AMD64 generation 1 and Armv8-A generation 2 Hyper-V VMs.

image
image
image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 VMware VM.

- Product: VMware® Workstation 17 Pro
- Version: 17.6.0 build-24238078
- Host OS version: Windows 11 Enterprise, 64-bit (Build 27695.1000) 10.0.27695
- Accelerate 3D graphics: on
- Firmware type: UEFI
- Host VBS Mode: on

image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on 战神Z8-KP7S2.

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on RedmiBook 16 (锐龙版).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Surface Pro (5th Gen).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on ROG Ally (2023).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on ProArt B550-CREATOR.

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Latitude D630.

图片

**Comment by MingcongBai** [comment]
Smoke test passed on LoongArch (THTF Chaorui L860-T2, 3A5000M).

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 generation 2, AMD64 generation 1 and Armv8-A generation 2 Hyper-V VMs.

image
image
image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 VMware VM.

- Product: VMware® Workstation 17 Pro
- Version: 17.6.0 build-24238078
- Host OS version: Windows 11 Enterprise, 64-bit (Build 27718.1000) 10.0.27718
- Accelerate 3D graphics: on
- Firmware type: UEFI
- Host VBS Mode: on

image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Latitude D630.

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on 战神Z8-KP7S2.

图片
图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on RedmiBook 16 (锐龙版).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Surface Pro (5th Gen).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on ROG Ally (2023).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on ProArt B550-CREATOR.

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 generation 2, AMD64 generation 1 and Armv8-A generation 2 Hyper-V VMs.

image
image
image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 VMware VM.

- Product: VMware® Workstation 17 Pro
- Version: 17.6.0 build-24238078
- Host OS version: Windows 11 Enterprise, 64-bit (Build 27718.1000) 10.0.27718
- Accelerate 3D graphics: on
- Firmware type: UEFI
- Host VBS Mode: on

image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on 战神Z8-KP7S2.

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on RedmiBook 16 (锐龙版).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Surface Pro (5th Gen).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on ROG Ally (2023).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Latitude D630.

image_2024-10-10_04-57-03

**Comment by KexyBiscuit** [comment]
Smoke testing passed on ProArt B550-CREATOR.

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 VMware VM.

- Product: VMware® Workstation 17 Pro
- Version: 17.6.1 build-24319023
- Host OS version: Windows 11 Enterprise, 64-bit (Build 27723.1000) 10.0.27723
- Accelerate 3D graphics: on
- Firmware type: UEFI
- Host VBS Mode: on

image

**Comment by MingcongBai** [comment]
Touchpad tested good on THTF Chaorui L860-T2, and my Logitech USB mouse was recognised correctly as an imPS/2 mouse.

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 generation 2, AMD64 generation 1 and Armv8-A generation 2 Hyper-V VMs.

image
image
image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 VMware VM.

- Product: VMware® Workstation 17 Pro
- Version: 17.6.1 build-24319023
- Host OS version: Windows 11 Enterprise, 64-bit (Build 27723.1000) 10.0.27723
- Accelerate 3D graphics: on
- Firmware type: UEFI
- Host VBS Mode: on

image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on 战神Z8-KP7S2 with Optimus on.
Smoke testing passed on 战神Z8-KP7S2 with NVIDIA GPU only and NVIDIA DRM KMS enabled.

image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on RedmiBook 16 (锐龙版).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Surface Pro (5th Gen).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on ROG Ally (2023).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Latitude D630.

image

**Review by OriginCode — DISMISSED** [review]

**Comment by KexyBiscuit** [comment]
Commit history squashed for easier merge, d6bad4d16e56fbce09da5c6b8a53cc91dc746971 is essentially the same as cc4a0c63b8ca0d4b46837fa7e98b2844c65f0311 for these packages.

```shell
kexybiscuit@ProArtB550-CREATOR [ aosc-os-abbs@linux-kernel-6.11.0 ] $ git log -1 --oneline
d6bad4d16e56 (HEAD -> linux-kernel-6.11.0, origin/linux-kernel-6.11.0) kernel-tools: update to 6.11.4
kexybiscuit@ProArtB550-CREATOR [ aosc-os-abbs@linux-kernel-6.11.0 ] $ git diff cc4a0c63b8ca0d4b46837fa7e98b2844c65f0311 runtime-kernel/linux-kernel
kexybiscuit@ProArtB550-CREATOR [ aosc-os-abbs@linux-kernel-6.11.0 ] $ git diff cc4a0c63b8ca0d4b46837fa7e98b2844c65f0311 runtime-kernel/linux+kernel
kexybiscuit@ProArtB550-CREATOR [ aosc-os-abbs@linux-kernel-6.11.0 ] $ git diff cc4a0c63b8ca0d4b46837fa7e98b2844c65f0311 app-admin/kernel-tools
kexybiscuit@ProArtB550-CREATOR [ aosc-os-abbs@linux-kernel-6.11.0 ] $ 
```

**Comment by KexyBiscuit** [comment]
> Commit history squashed for easier merge, [d6bad4d](https://github.com/AOSC-Dev/aosc-os-abbs/commit/d6bad4d16e56fbce09da5c6b8a53cc91dc746971) is essentially the same as [cc4a0c6](https://github.com/AOSC-Dev/aosc-os-abbs/commit/cc4a0c63b8ca0d4b46837fa7e98b2844c65f0311) for these packages.
> 
> ```shell
> kexybiscuit@ProArtB550-CREATOR [ aosc-os-abbs@linux-kernel-6.11.0 ] $ git log -1 --oneline
> d6bad4d16e56 (HEAD -> linux-kernel-6.11.0, origin/linux-kernel-6.11.0) kernel-tools: update to 6.11.4
> kexybiscuit@ProArtB550-CREATOR [ aosc-os-abbs@linux-kernel-6.11.0 ] $ git diff cc4a0c63b8ca0d4b46837fa7e98b2844c65f0311 runtime-kernel/linux-kernel
> kexybiscuit@ProArtB550-CREATOR [ aosc-os-abbs@linux-kernel-6.11.0 ] $ git diff cc4a0c63b8ca0d4b46837fa7e98b2844c65f0311 runtime-kernel/linux+kernel
> kexybiscuit@ProArtB550-CREATOR [ aosc-os-abbs@linux-kernel-6.11.0 ] $ git diff cc4a0c63b8ca0d4b46837fa7e98b2844c65f0311 app-admin/kernel-tools
> kexybiscuit@ProArtB550-CREATOR [ aosc-os-abbs@linux-kernel-6.11.0 ] $ 
> ```

Commit messages reworded.

**Review by MingcongBai — APPROVED** [review]

**Pull request merged**
