### PR TITLE
deno: update to 1.4.6

### PR DESCRIPTION
**Pull request by eatradish**
Topic Description
-----------------

deno: update to 1.4.6

- Use SRCS

Package(s) Affected
-------------------

deno 1.4.6

Security Update?
----------------

- [ ] Yes
- [x] No

Architectural Progress
----------------------

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`

### CODE REVIEW

**Review by MingcongBai — APPROVED** [review]

**Comment by eatradish** [comment]
ppc64el FTBFS: http://fars.ee/3qbq

**Comment by eatradish** [comment]
> ppc64el FTBFS: http://fars.ee/3qbq

Loongon3 too, the error is in the same place. (disable LTO after)

**Comment by MingcongBai** [comment]
@eatradish Deno may not even support these platforms, could be worth it to investigate what the upstream or other multi-architectural distributions have to say about this.

If Deno indeed does not support these architectures, mark FAIL_ARCH.

**Comment by eatradish** [comment]
AArch64 FTBFS: http://fars.ee/3H6C

**Comment by MingcongBai** [comment]
@eatradish Hmm, here a gn binary was executed (a “linux64” one, which I assume to be a name of x86/x86_64 assumption). Could this be stripped away from the source tree so that Deno uses system gn at build time?

**Comment by eatradish** [comment]
Upstream release deno 1.5.0, switch to new PR, Closing...

**Pull request closed without merging**
