### PR TITLE
fcitx5: update to 5.0.3

### PR DESCRIPTION
**Pull request by eatradish**
Topic Description
-----------------

fcitx5: update to 5.0.3

Package(s) Affected
-------------------

See `groups/fcitx5`

Security Update?
----------------

No

Build Order
-----------

Use `acbs-build groups/fcitx5` to build.

Architectural Progress
----------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

### CODE REVIEW

**Comment by eatradish** [comment]
`fcitx5-configtool` need `KF5 >= 5.76`, wait #2600 .

**Comment by eatradish** [comment]
LGTM on AMD64. but have error:

```
E2020-12-20 06:56:55.127806 luaaddonloader.cpp:20] Failed to load lua library: /usr/lib/liblua-5.3.so: undefined symbol: dlopen
E2020-12-20 06:56:55.127916 addonloader.cpp:57] Failed to create addon: luaaddonloader Failed to resolve lua functions.
```

And:

```
E1220 06:58:43.180892 1575082 deployment_tasks.cc:670] boost::filesystem::remove: Operation not permitted: "/tmp/rime.tools.Magputer.root.log.WARNING.20201217-134854.727592"
E1220 06:58:43.181033 1575082 deployment_tasks.cc:670] boost::filesystem::remove: Operation not permitted: "/tmp/rime.tools.Magputer.root.log.INFO.20201217-134854.727592"
```

**Comment by Fearyncess** [comment]
`fcitx5`, `fcitx5-chinese-addons`, `fcitx5-qt`, `fcitx5-gtk`, `libime` LGTM on AMD64
Fcitx5's iBus frontend also works good

**Review by MingcongBai — APPROVED** [review]

**Comment by Fearyncess** [comment]
图片
图片
fcitx5-configtool is good.

**Review by Fearyncess — APPROVED** [review]

**Comment by eatradish** [comment]
Wait this issue:

```
E2020-12-20 06:56:55.127806 luaaddonloader.cpp:20] Failed to load lua library: /usr/lib/liblua-5.3.so: undefined symbol: dlopen
```

**Pull request merged**
