### PR TITLE
firefox: update to 128.0.2

### PR DESCRIPTION
**Pull request by KexyBiscuit**
Topic Description
-----------------

- firefox: update to 128.0.2
    Also evaluate removing architecture specific workarounds.

Package(s) Affected
-------------------

- firefox: 128.0.2

Security Update?
----------------

No

Build Order
-----------

```
#buildit firefox
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Review by MingcongBai — COMMENTED** [review]
Tested good on AMD64:

image

**Comment by hanyuwei70** [comment]
tested on d2000 (arm64)
video & audio good. WebRTC good.

**Review by MingcongBai — DISMISSED** [review]
Tested good on LoongArch.

**Comment by OriginCode** [comment]
LGTM on amd64:
image

**Review by OriginCode — APPROVED** [review]

**Pull request merged**
