### PR TITLE
Cross Compiler Toolchain Survey (June 2024)

### PR DESCRIPTION
**Pull request by MingcongBai**
Topic Description
-----------------

- gcc+cross: bump REL for topic Revision Marking Guidelines
- gdb+cross*: drop, orphaned
    The main gdb package already ships with support for all targets, there is no
    longer the need to maintain cross GDB packages.
- gcc+cross: new, 13.2.0+glibc2.38+2-0
    Merge all architecture packages into one.
- binutils+cross-ppc64: drop, orphaned
    Afterglow cross compilers to be revisited on a later date.
- binutils+cross-powerpc: drop, orphaned
    Afterglow cross compilers to be revisited on a later date.

Package(s) Affected
-------------------

- gcc+cross-amd64: 13.2.0+glibc2.38+6-2
- gcc+cross-arm64: 13.2.0+glibc2.38+6-2
- gcc+cross-loongarch64: 13.2.0+glibc2.38+6-2
- gcc+cross-loongson3: 13.2.0+glibc2.38+6-2
- gcc+cross-ppc64el: 13.2.0+glibc2.38+6-2
- gcc+cross-riscv64: 13.2.0+glibc2.38+6-2

Security Update?
----------------

No

Build Order
-----------

```
#buildit gcc+cross
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by jiegec** [comment]
We can dedup the scripts further by symlinking?

**Comment by MingcongBai** [comment]
> We can dedup the scripts further by symlinking?

Let's see if ACBS handles symlinks in `autobuild/` properly...

**Comment by MingcongBai** [comment]
> We can dedup the scripts further by symlinking?

Nope, ACBS did not like that and just ignored them...

**Comment by MingcongBai** [comment]
Tested good building the Linux Kernel for all other five architectures on AMD64.

**Comment by MingcongBai** [comment]
Tested good on AArch64, LoongArch with the same test.

**Review by KexyBiscuit — APPROVED** [review]

**Pull request merged**
