### PR TITLE
wps-office: update to 11.1.0.11711

### PR DESCRIPTION
**Pull request by eatradish**
Topic Description
-----------------

- wps-office: update to 11.1.0.11711

Package(s) Affected
-------------------

- wps-office: 11.1.0.11711

Security Update?
----------------

No

Build Order
-----------

```
#buildit wps-office
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`

### CODE REVIEW

**Comment by eatradish** [comment]
@aosc-buildit-bot build

**Comment by eatradish** [comment]
@aosc-buildit-bot build

**Comment by eatradish** [comment]
@aosc-buildit-bot build

**Review by MingcongBai — APPROVED** [review]

**Comment by eatradish** [comment]
@aosc-buildit-bot build

**Pull request merged**
