### PR TITLE
opencl-registry-api and cpyrit-opencl

### PR DESCRIPTION
**Pull request by liushuyu**
OpenCL 2.0 compliant headers package and opencl based pyrit acceleration package

### CODE REVIEW

**Comment by MingcongBai** [comment]
We already have `opencl-registry-api` of the same version, you may exclude that from your pull request.

**Comment by MingcongBai** [comment]
By the way, please do me a favor by checking for left over `$PKGVER` definition in your `defines` before creating a PR.

**Comment by liushuyu** [comment]
No, this is  a new version

**Comment by MingcongBai** [comment]
> No, this is a new version

```
root [ nose@staging ] # apt search opencl-registry
Sorting... Done
Full Text Search... Done
opencl-registry-api/os3,os3,now 2.0-0 amd64 [installed]
  OpenCL (Open Computing Language) header files
```

Pretty sure I am not mistaken though...

**Comment by liushuyu** [comment]
With limited support of opencl 1.2

**Comment by MingcongBai** [comment]
Okay... I got it. I will merge now, and taking care of packaging from here.

Thanks a lot!

**Comment by MingcongBai** [comment]
@arthur2e5 My dear... is this one of your clones?

**Comment by Arthur2e5** [comment]
waffle.io/AOSC-Dev/aosc-os-abbs

**Comment by MingcongBai** [comment]
原来如此

**Comment by Arthur2e5** [comment]
Again, do not use the merge button. Do git pull --rebase=preserve somerepo someref.

**Comment by MingcongBai** [comment]
Okay...

**Pull request merged**
