### PR TITLE
Qt 6.4.2 Survey

### PR DESCRIPTION
**Pull request by WhiredPlanck**
Topic Description
-----------------

This PR is to update `qt-6` to 6.3.1 and fine tune some parameters.

Package(s) Affected
-------------------

- `qt-6` v6.4.2
- `html5lib-python` v1.1
- `qt6ct` v0.5 (new)

Security Update?
----------------

No

Build Order
-----------

```
html5lib-python qt-6 qt6ct
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
~~- [ ] PowerPC 64-bit (Little Endian) `ppc64el`~~ (suspended)
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
~~- [ ] PowerPC 64-bit (Little Endian) `ppc64el`~~ (suspended)
- [ ] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by WhiredPlanck** [comment]
OBS may switch to Qt 6 in its next stable version, and this PR will wait for it to test.

**Comment by WhiredPlanck** [comment]
> OBS may switch to Qt 6 in its next stable version, and this PR will wait for it to test.

Due to a lot of breaking changes of the new OBS, this PR may tested by other packages.

**Comment by eatradish** [comment]
obs with qt6 fucking no

**Comment by WhiredPlanck** [comment]
> obs with qt6 fucking no

Well, that day will come.

**Comment by WhiredPlanck** [comment]
qpwgraph LGTM on AMD64

qpwgraph requires Qt 6's Core, Gui, Widgets, Xml, Svg and Network components, this may prove that these components work well.

图片

**Comment by WhiredPlanck** [comment]
qt6ct LGTM on AMD64

qt6ct requires Qt 6's BuildInternals, Widgets, Concurrent and LinguistTools components, this may prove that they work well.

图片

**Comment by WhiredPlanck** [comment]
qbittorrent LGTM on AMD64

qbittorrent requires Qt 6's Core, Network, Sql, Xml, LinguistTools, DBus, Widgets and Svg components, this may prove that they work well.

图片

**Comment by WhiredPlanck** [comment]
Here are 3 packages pass the build test, this PR is ready for review.

**Comment by WhiredPlanck** [comment]
> Here are 3 packages pass the build test, this PR is ready for review.

Another package will be tested since qbittorrent can still build with Qt 5 and work well.

**UPDATE**: There is really few powerful software support or switch to Qt 6, so I think this is enough now.

**Comment by WhiredPlanck** [comment]
obs-studio LGTM on AMD64

https://user-images.githubusercontent.com/47623588/202719770-7bb4176e-1601-404e-9039-9775ecc730e3.mp4

**Comment by MingcongBai** [comment]
Superseded by #4441. Closing.

**Comment by WhiredPlanck** [comment]
> Superseded by #4441. Closing.

Thanks ~ I'm too busy / tired to finish this.

**Pull request closed without merging**
