### PR TITLE
linux-kernel-lts: update to 6.6.52

### PR DESCRIPTION
**Pull request by KexyBiscuit**
Topic Description
-----------------

- linux+kernel+lts: update to 6.6.52
- linux-kernel-lts: update to 6.6.52
    - Test results from 6.6.52-rc1 should be still valid.
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.6.52, current HEAD is 458835ca73f465b488a4349071a980fdbc866153.
- linux+kernel+lts: update to 6.6.52-rc1
- linux-kernel-lts: update to 6.6.52-rc1
    - Update more-uarches-for-kernel-6.1.79-6.8-rc3.patch.
    - Routine patch due diligence.
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.6.52-rc1, current HEAD is 3e4f2d59387ec79e8da568a85ebab4f42e305897.

Package(s) Affected
-------------------

- linux+kernel+lts: 2:6.6.52
- linux-kernel-lts-${__VER}: 6.6.52

Security Update?
----------------

No

Build Order
-----------

```
#buildit linux-kernel-lts linux+kernel+lts
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 generation 2, AMD64 generation 1 and Armv8-A generation 2 Hyper-V VMs.

image
image
image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 VMware VM.

- Product: VMware® Workstation 17 Pro
- Version: 17.6.0 build-24238078
- Host OS version: Windows 11 Enterprise, 64-bit (Build 27695.1000) 10.0.27695
- Accelerate 3D graphics: on
- Firmware type: UEFI
- Host VBS Mode: on

image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on 战神Z8-KP7S2.

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Surface Pro (5th Gen).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on RedmiBook 16 (锐龙版).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on ProArt B550-CREATOR.

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Latitude D630.

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on ROG Ally (2023).

图片

**Comment by MingcongBai** [comment]
Smoke testing passed on an Eaecis L71 laptop (LoongArch). cpufreq does not function but not a new issue.

**Review by MingcongBai — APPROVED** [review]

**Pull request merged**
