### PR TITLE
swift-im: Fix FTBFS (port to Qt 5.11)

### PR DESCRIPTION
**Pull request by RedL0tus**
Added one patch: https://github.com/RedL0tus/aosc-os-abbs/blob/swift-im/extra-web/swift-im/autobuild/patches/0000-fix-qtwebelement.patch

### CODE REVIEW

**Review by liushuyu — APPROVED** [review]
LGTM

**Review by liushuyu — CHANGES_REQUESTED** [review]
One thing to address though, please bump `REL` in `spec`

**Review by liushuyu — APPROVED** [review]

**Comment by liushuyu** [comment]
Have you pushed the package yet?

**Comment by RedL0tus** [comment]
@liushuyu Nope.

**Pull request merged**
