### PR TITLE
i2pd: update to 2.34.0

### PR DESCRIPTION
**Pull request by r4sas**
Topic Description
-----------------
i2pd: update to 2.34.0

Package(s) Affected
-------------------
i2pd

Security Update?
----------------

No, update of package in exceptions list

Architectural Progress
----------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

### CODE REVIEW

**Review by MingcongBai — APPROVED** [review]

**Comment by MingcongBai** [comment]
Thank you!

**Comment by MingcongBai** [comment]
Just for future reference, as we have now turned to a topic-based maintenance schedule, the Exception mechanism is no longer in effect.

See:

- [AOSC OS Topic-Based Maintenance Guidelines](https://wiki.aosc.io/developer/packaging/topic-based-maintenance-guideline/)
- [Tooling and Infrastructural Changes Required for the Topic-Based Transition (RFC)](https://wiki.aosc.io/developer/packaging/topic-based-tooling-infra-changes/)

**Comment by MingcongBai** [comment]
Sorry for faffing around with your pull request, I will now merge this commit and continue work in the `i2pd-2.34.0` branch.

**Comment by r4sas** [comment]
> Just for future reference, as we have now turned to a topic-based maintenance schedule, the Exception mechanism is no longer in effect.

Got it. Thank you.

**Pull request merged**
