### PR TITLE
Import new packages

### PR DESCRIPTION
**Pull request by liushuyu**
I need someone to double check these packages for me...
And I want to know if our repository has openCL headers (req. by cpyrit-opencl) and complete CUDA development environment (cpyrit-cuda)...

### CODE REVIEW

**Comment by MingcongBai** [comment]
Please, remove `$PKGVER` from `defines`. Other than that they look good to me (not tested).

**Comment by liushuyu** [comment]
OK, fixed

**Comment by MingcongBai** [comment]
> ... for CUDA is too big for me to download and install......

I would not recommend CUDA, the best you can do is to `PKGRECOM` it.

**Comment by MingcongBai** [comment]
Can I merge this batch for now or you want me to wait more on this?

**Comment by liushuyu** [comment]
You can merge this now.
CUDA and OpenCL seem far beyond me... And Do we have OpenCL and CUDA development packages?

**Comment by MingcongBai** [comment]
> CUDA and OpenCL seem far beyond me... And Do we have OpenCL and CUDA development packages?

We do. `libclc` and `cuda` respectively. However I am thinking of dropping `cuda` very soon.

**Comment by liushuyu** [comment]
OK, I will give a try...
If you don't use graphic card acceleration, you will **CRAZY** ... Because GPU can have more threads...

**Comment by MingcongBai** [comment]
I realized that. As of `cuda` I can either...

1. Figure out a way for it to work properly;
2. Figure it into an installer wrapper;

But before that... you can do `PKGRECOM` on `cuda`.

Thanks.

**Pull request merged**
