### PR TITLE
virtualbox: update to 7.1.2

### PR DESCRIPTION
**Pull request by xtexx**
Topic Description
-----------------

- virtualbox: update to 7.1.2

Package(s) Affected
-------------------

- virtualbox: 7.1.2
- virtualbox-guest: 7.1.2

Security Update?
----------------

No

Build Order
-----------

```
#buildit virtualbox
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`

### CODE REVIEW

**Comment by xtexx** [comment]
LGTM on AMD64, known 3D-accel issue is not yet resolved

image

**Comment by MingcongBai** [comment]
> LGTM on AMD64, known 3D-accel issue is not yet resolved
> 
> image

Actually, 3D acceleration works for me? At least the configuration dialogue appears to work now, and my deepin V23 VM seems to have gotten much quicker with this enablement.

**Comment by MingcongBai** [comment]
For reference:

- https://www.virtualbox.org/ticket/22173
- https://www.virtualbox.org/wiki/Changelog-7.1

**Comment by MingcongBai** [comment]
@xtexChooser Indicated that on their computer, they weren't able to boot a Windows VM with 3D acceleration enabled `NS_ERROR_FAILURE(0x80004005)`, but I wasn't able to reproduce this (AMD Ryzen 7 8845H + Radeon 780M).

**Review by MingcongBai — APPROVED** [review]
Let's merge this for now - at least 3D acceleration now works on some machines.

**Pull request merged**
