### PR TITLE
linux-kernel-lts: update to 6.6.50

### PR DESCRIPTION
**Pull request by KexyBiscuit**
Topic Description
-----------------

- linux+kernel+lts: update to 6.6.50
- linux-kernel-lts: update to 6.6.50
    - Bye mips64r6el.
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.6.50, current HEAD is 2382ea11d9ee0e8df9d8bbffb46d6a39a82d1bd1.

Package(s) Affected
-------------------

- linux+kernel+lts: 2:6.6.50
- linux-kernel-lts-${__VER}: 6.6.50

Security Update?
----------------

No

Build Order
-----------

```
#buildit linux-kernel-lts linux+kernel+lts
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 VMware VM.

- Product: VMware® Workstation 17 Pro
- Version: 17.6.0 build-24238078
- Host OS version: Windows 11 Enterprise, 64-bit (Build 27695.1000) 10.0.27695
- Accelerate 3D graphics: on
- Firmware type: UEFI
- Host VBS Mode: on

image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 generation 2, AMD64 generation 1 and Armv8-A generation 2 Hyper-V VMs.

image
image
image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on RedmiBook 16 (锐龙版).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on ROG Ally (2023).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on ProArtB550-CREATOR.

图片

**Comment by stdmnpkg** [comment]
works on my loongarch64 machine

image

**Review by stdmnpkg — APPROVED** [review]

**Pull request merged**
