### PR TITLE
audacity: update to 2.3.1

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by KexyBiscuit** [comment]
> We’ve restored support for Linux which was missing in 2.3.0.

So I'll merge this immediately.

**Comment by MingcongBai** [comment]
@KexyBiscuit Please also cherry-pick this into Stable - this is a patch-level update.

@luzpaz Thanks for your contribution! As a community rule, you are now eligible for an @aosc.io (also @aosc.xyz, @anthonos.org as redirects) e-mail address. Please contact me via e-mail for more details.

**Comment by KexyBiscuit** [comment]
@MingcongBai d212df6 :shipit:

**Comment by MingcongBai** [comment]
@KexyBiscuit Thanks

**Pull request merged**
