### PR TITLE
libvpx: update to 1.15.0

### PR DESCRIPTION
**Pull request by KexyBiscuit**
Topic Description
-----------------

- libvpx: update patches for LoongArch
- libvpx: update Breaks
- groups/libvpx-rebuilds: replace gst-plugins* with gstreamer
- gstreamer: rebuild for libvpx
- Revert "gst-plugins-good-1-0: rebuild for libvpx"
    This reverts commit 3b22c1b6223245059e0cfd9e78337e5108b71d2a.
- xpra: rebuild for libvpx
- toxcore: rebuild for libvpx
- vlc: rebuild for libvpx
- handbrake: rebuild for libvpx
- gst-plugins-good-1-0: rebuild for libvpx

... and 13 more commits

Package(s) Affected
-------------------

- avidemux: 2.8.1-3
- ffmpeg: 7.1-2
- gstreamer: 1.24.7-2
- handbrake: 1.8.2-1
- libopenglrecorder: 0.1.0-6
- libvpx: 1.15.0
- toxcore: 1:0.2.18-1
- virtualbox: 7.1.4-1
- virtualbox-guest: 7.1.4-1
- vlc: 3.0.21-4
- xine-lib: 1.2.13-3
- xpra: 6.1.2-1

Security Update?
----------------

No

Build Order
-----------

```
#buildit libvpx:-pkgbreak groups/libvpx-rebuilds libvpx
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by KexyBiscuit** [comment]
LTO failed on 64-bit LoongArch.

```
lto1: fatal error: target specific builtin not available
```

**Comment by KexyBiscuit** [comment]
After disabling LTO on 64-bit LoongArch...

```
/usr/bin/ld: vpx_dsp/vpx_dsp_rtcd.c.o: in function `setup_rtcd_internal':
/var/cache/acbs/build/acbs.3l9gdc7o/libvpx-1.15.0/././vpx_dsp_rtcd.h:1733:(.text+0x20c): undefined reference to `vpx_quantize_b_lsx'
/usr/bin/ld: /var/cache/acbs/build/acbs.3l9gdc7o/libvpx-1.15.0/././vpx_dsp_rtcd.h:1733:(.text+0x210): undefined reference to `vpx_quantize_b_lsx'
/usr/bin/ld: /var/cache/acbs/build/acbs.3l9gdc7o/libvpx-1.15.0/././vpx_dsp_rtcd.h:1733:(.text+0x224): undefined reference to `vpx_quantize_b_32x32_lsx'
/usr/bin/ld: /var/cache/acbs/build/acbs.3l9gdc7o/libvpx-1.15.0/././vpx_dsp_rtcd.h:1733:(.text+0x228): undefined reference to `vpx_quantize_b_32x32_lsx'
collect2: error: ld returned 1 exit status
```

**Comment by KexyBiscuit** [comment]
Smoke testing passed on 64-bit LoongArch.

```shell
(ssh)kexybiscuit@XA612A0 [ [REDACTED] ] $ ffmpeg -i circle.mov        -map v -c:v libvpx-vp9 -pass 1 -pix_fmt yuv420p -f null /dev/null && ffmpeg -i circle.mov        -map v -c:v libvpx-vp9 -pass 2 -pix_fmt yuv420p circle_VP9.webm
ffmpeg version 7.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (GCC) 20230727 (AOSC OS, Core)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-fontconfig --enable-gnutls --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-runtime-cpudetect --enable-shared --enable-swresample --enable-vdpau --enable-version3 --enable-vaapi --enable-libaom --enable-libsmbclient --enable-libsvtav1
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'circle.mov':
  Metadata:
    major_brand     : qt
    minor_version   : 537199360
    compatible_brands: qt
    creation_time   : 2024-11-16T02:13:56.000000Z
  Duration: 00:00:08.38, start: 0.000000, bitrate: 3596738 kb/s
  Stream #0:0[0x1](eng): Video: qtrle (rle  / 0x20656C72), rgb24(progressive), 3840x2160, 3594201 kb/s, SAR 1:1 DAR 16:9, 24 fps, 24 tbr, 24 tbn (default)
      Metadata:
        creation_time   : 2024-11-16T02:13:56.000000Z
        handler_name    : Apple Video Media Handler
        vendor_id       : appl
        encoder         : Animation
        timecode        : 00:00:00:00
  Stream #0:1[0x2](eng): Audio: pcm_s16le (sowt / 0x74776F73), 48000 Hz, stereo, s16, 1536 kb/s (default)
      Metadata:
        creation_time   : 2024-11-16T02:13:56.000000Z
        handler_name    : Apple Sound Media Handler
        vendor_id       :
        timecode        : 00:00:00:00
  Stream #0:2[0x3](eng): Data: none (tmcd / 0x64636D74), 0 kb/s (default)
      Metadata:
        creation_time   : 2024-11-16T02:13:56.000000Z
        handler_name    : Time Code Media Handler
        timecode        : 00:00:00:00
Stream mapping:
  Stream #0:0 -> #0:0 (qtrle (native) -> vp9 (libvpx-vp9))
Press [q] to stop, [?] for help
[libvpx-vp9 @ 0x55556af7c180] v1.15.0
[libvpx-vp9 @ 0x55556af7c180] Neither bitrate nor constrained quality specified, using default CRF of 32
Output #0, null, to '/dev/null':
  Metadata:
    major_brand     : qt
    minor_version   : 537199360
    compatible_brands: qt
    encoder         : Lavf61.7.100
  Stream #0:0(eng): Video: vp9, yuv420p(tv, progressive), 3840x2160 [SAR 1:1 DAR 16:9], q=2-31, 24 fps, 24 tbn (default)
      Metadata:
        creation_time   : 2024-11-16T02:13:56.000000Z
        handler_name    : Apple Video Media Handler
        vendor_id       : appl
        timecode        : 00:00:00:00
        encoder         : Lavc61.19.100 libvpx-vp9
      Side data:
        cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
[out#0/null @ 0x55556af7fce0] video:0KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
[out#0/null @ 0x55556af7fce0] Output file is empty, nothing was encoded
frame=    0 fps=0.0 q=0.0 Lsize=N/A time=N/A bitrate=N/A speed=N/A
ffmpeg version 7.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (GCC) 20230727 (AOSC OS, Core)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-fontconfig --enable-gnutls --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-runtime-cpudetect --enable-shared --enable-swresample --enable-vdpau --enable-version3 --enable-vaapi --enable-libaom --enable-libsmbclient --enable-libsvtav1
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'circle.mov':
  Metadata:
    major_brand     : qt
    minor_version   : 537199360
    compatible_brands: qt
    creation_time   : 2024-11-16T02:13:56.000000Z
  Duration: 00:00:08.38, start: 0.000000, bitrate: 3596738 kb/s
  Stream #0:0[0x1](eng): Video: qtrle (rle  / 0x20656C72), rgb24(progressive), 3840x2160, 3594201 kb/s, SAR 1:1 DAR 16:9, 24 fps, 24 tbr, 24 tbn (default)
      Metadata:
        creation_time   : 2024-11-16T02:13:56.000000Z
        handler_name    : Apple Video Media Handler
        vendor_id       : appl
        encoder         : Animation
        timecode        : 00:00:00:00
  Stream #0:1[0x2](eng): Audio: pcm_s16le (sowt / 0x74776F73), 48000 Hz, stereo, s16, 1536 kb/s (default)
      Metadata:
        creation_time   : 2024-11-16T02:13:56.000000Z
        handler_name    : Apple Sound Media Handler
        vendor_id       :
        timecode        : 00:00:00:00
  Stream #0:2[0x3](eng): Data: none (tmcd / 0x64636D74), 0 kb/s (default)
      Metadata:
        creation_time   : 2024-11-16T02:13:56.000000Z
        handler_name    : Time Code Media Handler
        timecode        : 00:00:00:00
Stream mapping:
  Stream #0:0 -> #0:0 (qtrle (native) -> vp9 (libvpx-vp9))
Press [q] to stop, [?] for help
[libvpx-vp9 @ 0x5555792dbe80] v1.15.0
[libvpx-vp9 @ 0x5555792dbe80] Neither bitrate nor constrained quality specified, using default CRF of 32
Output #0, webm, to 'circle_VP9.webm':
  Metadata:
    major_brand     : qt
    minor_version   : 537199360
    compatible_brands: qt
    encoder         : Lavf61.7.100
  Stream #0:0(eng): Video: vp9, yuv420p(tv, progressive), 3840x2160 [SAR 1:1 DAR 16:9], q=2-31, 24 fps, 1k tbn (default)
      Metadata:
        creation_time   : 2024-11-16T02:13:56.000000Z
        handler_name    : Apple Video Media Handler
        vendor_id       : appl
        timecode        : 00:00:00:00
        encoder         : Lavc61.19.100 libvpx-vp9
      Side data:
        cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
[out#0/webm @ 0x5555792dfaa0] video:15611KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.014432%
frame=  201 fps=0.2 q=32.0 Lsize=   15613KiB time=00:00:08.37 bitrate=15271.8kbits/s speed=0.00687x
```

**Comment by MingcongBai** [comment]
ffmpeg+32 FTBFS, investigation pending.

**Review by MingcongBai — APPROVED** [review]

**Pull request merged**
