### PR TITLE
ispc: update to 1.25.1

### PR DESCRIPTION
**Pull request by ouankou**
Topic Description
-----------------

- ispc: update to 1.25.1
    Co-authored-by: Anjia Wang (@ouankou) <anjia@ouankou.com>

Package(s) Affected
-------------------

- ispc: 1.25.1

Security Update?
----------------

No

Build Order
-----------

```
#buildit ispc
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`

### CODE REVIEW

**Comment by ouankou** [comment]
Tested on i9-11950H.
Test code: https://git.sr.ht/~ouankou/whiteboard/tree/main/item/ispc
```bash
(ssh)ouankou@ei [ ispc@main ] $ ispc --version
Intel(r) Implicit SPMD Program Compiler (Intel(r) ISPC), 1.25.1 (build 1.25.1 @ 20241020, LLVM 18.1.8)
(ssh)ouankou@ei [ ispc@main ] $ ispc axpy.ispc -o axpy.o --target=avx2
(ssh)ouankou@ei [ ispc@main ] $ g++ -o axpy axpy.cpp axpy.o -lm
(ssh)ouankou@ei [ ispc@main ] $ ./axpy
Passed
```

**Comment by rickliu2000** [comment]
Looks okay to me

**Review by rickliu2000 — COMMENTED** [review]
Looks okay to me

**Review by rickliu2000 — APPROVED** [review]
Looks okay to me

**Pull request merged**
