### PR TITLE
Darktable 3.8.0

### PR DESCRIPTION
**Pull request by cthbleachbit**
Topic Description
-----------------

This PR updates darktable to 3.8.0, a major feature update.

Package(s) Affected
-------------------

* exiv2
* libraw
* gmic
* lua-5.4
* darktable

Build Order
-----------

exiv2 libraw gmic lua-5.4 darktable

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

### CODE REVIEW

**Comment by cthbleachbit** [comment]
Marked draft as this PR would benefit from #3732.

**Comment by MingcongBai** [comment]
@cthbleachbit Honestly, merge it with #3732.

**Comment by cthbleachbit** [comment]
> @cthbleachbit Honestly, merge it with #3732.

I'd prefer to keep things in separate PRs for clarity as this PR introduces new dependencies as well...

**Comment by MingcongBai** [comment]
@cthbleachbit Got it.

**Comment by cthbleachbit** [comment]
Darktable 3.8 functionality has been fully tested over last 2 weeks and is known to work on amd64 and arm64.

**Review by MingcongBai — APPROVED** [review]

**Comment by cthbleachbit** [comment]
changes approved - assuming lgtm

**Comment by MingcongBai** [comment]
@cthbleachbit Да, конечно.

**Pull request merged**
