### PR TITLE
trojan: update to 1.4.4

### PR DESCRIPTION
**Pull request by GreaterFire**

### CODE REVIEW

**Comment by MingcongBai** [comment]
Wondering if you would care to join our community channel at #aosc or via Telegram (the group which you were in)? I have two members of the community already questioning some of the security design choices in your project, it will be helpful if you could answer them or at least put out a statement (I can help to locate these particular members).

Until you could do that, your PR will be put on hold (and marked `stalled`). I hope for your understanding.

**Comment by MingcongBai** [comment]
The party of concern (ref. @Cargress, current ID on Telegram) would like to retract this statement. Sorry for my interrogative tone above.

Thanks for your PR, and we look forward to see more from you.

**Comment by MingcongBai** [comment]
@GreaterFire Also as a note for future PRs, we will be adding `trojan` to our Monthly Wave Exception under category 3 (essential to basic Internet access in certain regions) - therefore, your next PR should be made against the `bugfix` branch for immediate build and availability.

**Comment by GreaterFire** [comment]
Thank you.

**Pull request merged**
