### PR TITLE
workflows: update status in comments

### PR DESCRIPTION
**Pull request by KexyBiscuit**
- Thank @outloudvi for the idea.

### CODE REVIEW

**Review by MingcongBai — APPROVED** [review]

**Comment by outloudvi** [comment]
I'm not really sure if returning an empty package list will trigger a failure. I'll get it cloned on my repo and have a try later...

**Comment by KexyBiscuit** [comment]
@outloudvi I just tested it in my fork, sending `/build 不支持中文包名` will fail the workflow.

**Review by outloudvi — APPROVED** [review]
LGTM :)

**Comment by KexyBiscuit** [comment]
GitHub will trim blank spaces at ending of the line, at least on web, so I think it's not possible to invoke the command with absolutely no packages specified.

**Pull request merged**
