### PR TITLE
chromium survey 20220328

### PR DESCRIPTION
**Pull request by CamberLoid**
Topic Description
-----------------

This pull request will update `chromium` and `google-chrome` to 100.0.4896.60 . This upgrade involves several security upgrade to Chrome and Chromium.

Package(s) Affected
-------------------

`chromium`
`google-chrome`

Security Update?
----------------

Yes. #3887 

Test Build(s) Done
------------------

**Primary Architectures**

- [x] `google-chrome` AMD64 `amd64`   
- [x] `chromium` AMD64 `amd64`
- [x] `chromium` AArch64 `arm64`
    

Update(s) Uploaded to Stable
----------------------------

Not applicable as #3901  is opened

### CODE REVIEW

**Comment by CamberLoid** [comment]
This PR will stay draft for a while, and packages will be available in testing branch `deb https://repo.aosc.io/debs chromium-survey-20220328 main` for testing purpose.

**Comment by CamberLoid** [comment]
`chromium` and `google-chrome` 100.0.4896.60-1 have been pushed to our repository, `chromium-survey-20220328` branch.
Tests for chromium required.

**Comment by CamberLoid** [comment]
Currently, chromium has gpu/webgl issues
```
[19933:19933:0401/104826.754066:ERROR:gl_surface_egl.cc(808)] EGL Driver message (Error) eglCreateContext: eglCreateContext
[19933:19933:0401/104826.754275:ERROR:gl_context_egl.cc(352)] eglCreateContext failed with error EGL_SUCCESS
[19933:19933:0401/104826.754577:ERROR:gpu_channel_manager.cc(831)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[19933:19933:0401/104826.754652:ERROR:shared_image_stub.cc(537)] SharedImageStub: unable to create context
[19933:19933:0401/104826.754716:ERROR:gpu_channel.cc(571)] GpuChannel: Failed to create SharedImageStub
```

image

Seems our chromium doesn't have ANGEL, or hardware webgl acceleration enabled, and composite hardware acceleration enabled. This requires deeper investigation.
(left: archlinux-shipped chromium / middle: chromium(qemu-ed aosc) / right: google-chrome(qemu-ed aosc))

**Comment by CamberLoid** [comment]
image

Old version 97.x does not report WebGL issues and composite issue.

**Comment by CamberLoid** [comment]
> Currently, chromium has gpu/webgl issues
> 
> ```
> [19933:19933:0401/104826.754066:ERROR:gl_surface_egl.cc(808)] EGL Driver message (Error) eglCreateContext: eglCreateContext
> [19933:19933:0401/104826.754275:ERROR:gl_context_egl.cc(352)] eglCreateContext failed with error EGL_SUCCESS
> [19933:19933:0401/104826.754577:ERROR:gpu_channel_manager.cc(831)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
> [19933:19933:0401/104826.754652:ERROR:shared_image_stub.cc(537)] SharedImageStub: unable to create context
> [19933:19933:0401/104826.754716:ERROR:gpu_channel.cc(571)] GpuChannel: Failed to create SharedImageStub
> ```
> 
> image
> 
> Seems our chromium doesn't have ANGEL, or hardware webgl acceleration enabled, and composite hardware acceleration enabled. This requires deeper investigation. (left: archlinux-shipped chromium / middle: chromium(qemu-ed aosc) / right: google-chrome(qemu-ed aosc))

Solved in commit https://github.com/AOSC-Dev/aosc-os-abbs/pull/3889/commits/b160983ca4b71e29061e2f0938a0ce61bfce42cc

**Comment by CamberLoid** [comment]
Got new errors
```
[3129:3129:0404/092250.658936:ERROR:angle_platform_impl.cc(44)] Display.cpp:966 (initialize): ANGLE Display::initialize error 0: Internal Vulkan error (-3): Initialization of an object could not be completed for implementation-specific reasons, in ../../third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp, initialize:1271.
[3129:3129:0404/092250.659357:ERROR:gl_surface_egl.cc(808)] EGL Driver message (Critical) eglInitialize: Internal Vulkan error (-3): Initialization of an object could not be completed for implementation-specific reasons, in ../../third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp, initialize:1271.
[3129:3129:0404/092250.659969:ERROR:gl_surface_egl.cc(1430)] eglInitialize Vulkan failed with error EGL_NOT_INITIALIZED, trying next display type
[3129:3129:0404/092250.781240:ERROR:gl_angle_util_vulkan.cc(189)] Failed to retrieve vkGetInstanceProcAddr
[3129:3129:0404/092250.781359:ERROR:vulkan_instance.cc(91)] Failed to get vkGetInstanceProcAddr pointer from ANGLE.
```

Investigation in progress.

**Comment by CamberLoid** [comment]
> Got new errors
> ```
> [3129:3129:0404/092250.658936:ERROR:angle_platform_impl.cc(44)] Display.cpp:966 (initialize): ANGLE Display::initialize error 0: Internal Vulkan error (-3): Initialization of an object could not be completed for implementation-specific reasons, in ../../third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp, initialize:1271.
> [3129:3129:0404/092250.659357:ERROR:gl_surface_egl.cc(808)] EGL Driver message (Critical) eglInitialize: Internal Vulkan error (-3): Initialization of an object could not be completed for implementation-specific reasons, in ../../third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp, initialize:1271.
> [3129:3129:0404/092250.659969:ERROR:gl_surface_egl.cc(1430)] eglInitialize Vulkan failed with error EGL_NOT_INITIALIZED, trying next display type
> [3129:3129:0404/092250.781240:ERROR:gl_angle_util_vulkan.cc(189)] Failed to retrieve vkGetInstanceProcAddr
> [3129:3129:0404/092250.781359:ERROR:vulkan_instance.cc(91)] Failed to get vkGetInstanceProcAddr pointer from ANGLE.
> ```
> 
> Investigation in progress. 

The issues above seem not to have negative impact on normal usage, and chrome://gpu doesn't report any more major errors comparing to binpacks `google-chrome`. Removed labels `investigation` and `no-fix-yet`. 

Investigation of aforementioned issues will be opened in new topics.

Marking this PR Ready-for-review.

**Review by MingcongBai — APPROVED** [review]

**Comment by CamberLoid** [comment]
According to the testing report of `arm64` from @OriginCode , there is no negative major issues of chromium on arm64 platforms. This PR will be merged immediately.

**Pull request merged**
