### PR TITLE
pygit2: update to 1.7.0

### PR DESCRIPTION
**Pull request by WhiredPlanck**
Topic Description
-----------------

Update `pygit2` to 1.7.0.

Package(s) Affected
-------------------

`pygit2`

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

### CODE REVIEW

**Comment by KexyBiscuit** [comment]
```
In file included from src/blob.h:34,
                 from src/blob.c:30:
src/types.h:36:2: error: #error You need a compatible libgit2 version (1.3.x)
   36 | #error You need a compatible libgit2 version (1.3.x)
      |  ^~~~~
error: command 'gcc' failed with exit status 1
```

**Comment by WhiredPlanck** [comment]
LGTM on AMD64

image

**Review by MingcongBai — DISMISSED** [review]

**Review by MingcongBai — APPROVED** [review]

**Pull request merged**
