### PR TITLE
linux-kernel-lts: update to 6.6.56

### PR DESCRIPTION
**Pull request by KexyBiscuit**
Topic Description
-----------------

- linux-kernel: unset `CONFIG_USB_ONBOARD_HUB` to fix boot livekit on MacBook Pro Mid 2010
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux+kernel+lts: update to 6.6.56
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel-lts: update to 6.6.56
    - Nearly identical with 6.6.55-rc1.
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.6.56, current HEAD is 523871f4606ee9df6f13caedfa24df4d38a96e96.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel-lts: update Power ISA config for 6.6.55-rc1
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel-lts: update Armv8-A AArch64 config
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel-lts: update config for 6.6.55-rc1
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux+kernel+lts: update to 6.6.55
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel-lts: update to 6.6.55-rc1
    - Routine patch due diligence for upstream releases.
    - Now following contribution guidelines of Android common kernels <https://android.googlesource.com/kernel/common/+/refs/heads/android-mainline/README.md>.
    - Update patch from kernel_compiler_patch.
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.6.55-rc1, current HEAD is 6b41bd9454bcd16af3be84269a114f91da540291.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>

Package(s) Affected
-------------------

- linux+kernel+lts: 2:6.6.56
- linux-kernel-lts-${__VER}: 6.6.56

Security Update?
----------------

No

Build Order
-----------

```
#buildit linux-kernel-lts linux+kernel+lts
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 generation 2, AMD64 generation 1 and Armv8-A generation 2 Hyper-V VMs.

image
image
image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 VMware VM.

- Product: VMware® Workstation 17 Pro
- Version: 17.6.0 build-24238078
- Host OS version: Windows 11 Enterprise, 64-bit (Build 27718.1000) 10.0.27718
- Accelerate 3D graphics: on
- Firmware type: UEFI
- Host VBS Mode: on

image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on 战神Z8-KP7S2.

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on RedmiBook 16 (锐龙版).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Surface Pro (5th Gen).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on ROG Ally (2023).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Latitude D630.

image_2024-10-10_05-24-14

**Comment by KexyBiscuit** [comment]
Smoke testing passed on ProArt B550-CREATOR.

图片

**Comment by MingcongBai** [comment]
LGTM on LoongArch (THTF Chaorui L860-T2), also verified that PixArt patch v2 worked well with both the touchpad and a USB Logitech mouse.

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 VMware VM.

- Product: VMware® Workstation 17 Pro
- Version: 17.6.1 build-24319023
- Host OS version: Windows 11 Enterprise, 64-bit (Build 27723.1000) 10.0.27723
- Accelerate 3D graphics: on
- Firmware type: UEFI
- Host VBS Mode: on

image

**Review by MingcongBai — APPROVED** [review]
Tested good with fix for MacBook Pro 15'' (Mid-2010).

**Pull request merged**
