### PR TITLE
trojan: update to 1.10.0

### PR DESCRIPTION
**Pull request by GreaterFire**

### CODE REVIEW

**Comment by eatradish** [comment]
```
VER=1.10.0
REL=1
```

@GreaterFire Please remove `REL`

**Comment by GreaterFire** [comment]
@eatradish Done.

**Review by liushuyu — APPROVED** [review]

**Review by eatradish — APPROVED** [review]

**Comment by MingcongBai** [comment]
Re-targetting for Stable, due to exceptions as described [here](https://wiki.aosc.io/developers/aosc-os/cycle-exceptions).

**Comment by MingcongBai** [comment]
Thanks! @GreaterFire

**Comment by MingcongBai** [comment]
Oops... Sorry I've made a mistake. I will re-commit these changes in Stable.

@GreaterFire In the future, please PR directly to Stable.

**Pull request merged**
