### PR TITLE
dog: new, 0.1.0

### PR DESCRIPTION
**Pull request by CamberLoid**
Topic Description
-----------------

Add new package `dog` in response to [pakreq 1001](https://pakreq.aosc.io/detail/1001)

Package(s) Affected
-------------------

`dog` v0.1.0

`rexml` v3.2.5
`kramdown` v2.3.1
`nokogiri` v1.13.3
`racc` v1.6.0
`mini-portile` v2.8.0
`ronn-ng` v0.9.1

Security Update?
----------------

No.

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by CamberLoid** [comment]
btw FTBFS under riscv64(with qemu user mode)

ACBS Log:

```
-------------------------------------------------------------------------- Welcome to ACBS - 20211125 --------------------------------------------------------------------------
[INFO]: Searching and resolving dependencies...
[4/5] zlib-staticll
[ERROR]: Found a loop in the dependency graph: ghc

[CRIT]: Oops! RuntimeError: Dependencies NOT resolved. Couldn't continue!
error: Build failed with status: 1
info: Ciel created a check-point: ./STATES/dog-1647196716.ciel-ckpt
```

**Comment by MingcongBai** [comment]
@CamberLoid The best thing to do (since there is no Haskell support for RISC-V) is to somehow strip pandoc build dependency out for RISC-V via BUILDDEP__RISCV64.

**Comment by CamberLoid** [comment]
Cherry-picked ronn-ng and its dependencies from zram-generator-1.1.1-new
Request review @WhiredPlanck .

I will try to build for amd64/arm64(qemu)/riscv64(qemu)/ppc64el(qemu)

**Comment by CamberLoid** [comment]
@CamberLoid Seems good to me on amd64, qemu-arm64/ppc64el/riscv64

**Comment by CamberLoid** [comment]
Screenshots:
amd64
image

arm64/qemu
image

ppc64el/qemu
image

riscv64/qemu
image

**Review by WhiredPlanck — APPROVED** [review]

**Comment by CamberLoid** [comment]
All package pushed to repo.aosc.io.
Pakreq finished.

**Pull request merged**
