### PR TITLE
gnome-3.38: update GNOME desktop to 3.38.x

### PR DESCRIPTION
**Pull request by MingcongBai**
Topic Description
-----------------

Update GNOME stack to 3.38, rebuild packages where applicable.

Package(s) Affected
-------------------

- `groups/gnome-3.38`

Testing notes:

- GNOME 3.38.x, and all extensions.
- Budgie Desktop 10.5.2.
- Phosh, possibly on a Pine Phone (@Icenowy *wink-wink*).

Security Update?
----------------

No

Build Order
-----------

`groups/gnome-3.38` contains all necessary build directions for ACBS.

Architectural Progress
----------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

### CODE REVIEW

**Comment by OriginCode** [comment]
Failed to launch `gnome-tweak`:
```
Traceback (most recent call last):
  File "/bin/gnome-tweaks", line 15, in <module>
    gi.require_version("Handy", "0.0")
  File "/usr/lib/python3.8/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Handy not available for version 0.0
```

**Comment by MingcongBai** [comment]
@OriginCode Is libhandy-0 installed on your system?

**Comment by OriginCode** [comment]
> @OriginCode Is libhandy-0 installed on your system?

No. It's not a dep.
Successfully launched `gnome-tweaks` after installing `libhandy-0`.

**Comment by MingcongBai** [comment]
@OriginCode Got it. I will address this in the morning (UTC -8).

**Comment by OriginCode** [comment]
`chrome-gnome-shell` doesn't work.
```
Traceback (most recent call last):
  File "/bin/chrome-gnome-shell", line 16, in <module>
    from gi.repository import GLib, Gio
ImportError: No module named gi.repository
```

**Comment by MingcongBai** [comment]
@OriginCode Oops. PyGObject is now only available for Python 3 (this is one of the affected packages). Pending review on all pygobject-3 revdeps.

**Comment by MingcongBai** [comment]
All issues noted above have already been fixed with the additional commits that followed.

**Comment by OriginCode** [comment]
Terminator:
```
Traceback (most recent call last):
  File "/bin/terminator", line 48, in <module>
    import terminatorlib.optionparse
  File "/usr/lib/python3.8/site-packages/terminatorlib/optionparse.py", line 24, in <module>
    from . import config
  File "/usr/lib/python3.8/site-packages/terminatorlib/config.py", line 75, in <module>
    from configobj import ConfigObj, flatten_errors
ModuleNotFoundError: No module named 'configobj'
```

**Comment by MingcongBai** [comment]
@OriginCode Ugh. Yet another dependency issue, will fix ASAP.

**Comment by MingcongBai** [comment]
> Terminator:
> 
> ```
> Traceback (most recent call last):
>   File "/bin/terminator", line 48, in <module>
>     import terminatorlib.optionparse
>   File "/usr/lib/python3.8/site-packages/terminatorlib/optionparse.py", line 24, in <module>
>     from . import config
>   File "/usr/lib/python3.8/site-packages/terminatorlib/config.py", line 75, in <module>
>     from configobj import ConfigObj, flatten_errors
> ModuleNotFoundError: No module named 'configobj'
> ```

Addressed with the latest commit.

**Comment by OriginCode** [comment]
> > Terminator:
> > ```
> > Traceback (most recent call last):
> >   File "/bin/terminator", line 48, in <module>
> >     import terminatorlib.optionparse
> >   File "/usr/lib/python3.8/site-packages/terminatorlib/optionparse.py", line 24, in <module>
> >     from . import config
> >   File "/usr/lib/python3.8/site-packages/terminatorlib/config.py", line 75, in <module>
> >     from configobj import ConfigObj, flatten_errors
> > ModuleNotFoundError: No module named 'configobj'
> > ```
> 
> Addressed with the latest commit.

Terminator LGTM now:
image

**Review by cthbleachbit — APPROVED** [review]

**Pull request merged**
