### PR TITLE
Network Utilities (network-base) Survey 20221209

### PR DESCRIPTION
**Pull request by MingcongBai**
Topic Description
-----------------

This topic surveys network utility updates, improving scripting quality where applicable.

Note: Go 1.19.4 is included in this topic, as the updated Clash (`clash`) requires Go >= 1.19.

Package(s) Affected
-------------------

- [x] `android-platform-tools` v31.0.3p1-1
- [x] `arp-scan` v1.9.8
- [x] `baidupcs-go` v3.8.7-1
- [x] `bcc` v0.25.0
- [x] `bind` v9.16.33-1
- [x] `bluez` v5.66
- [x] `bpftrace` v0.16.0
- [x] `ccat` v1.1.0+git20201007-1
- [x] `cf-tool` v1.0.0-2
- [x] `clash` v1.12.0
- [x] `delve` v1.8.3-1
- [x] `dep` v0.5.4-15
- [x] `direnv` v2.31.0-1
- [x] `dnscrypt` v2.1.1-1
- [x] `dnsmasq` v2.88
- [x] `elvish` v0.18.0-2
- [x] `ethtool` v6.0
- [x] `frp` v0.42.0-1
- [x] `fzf` v0.30.0-1
- [x] `geoipupdate` v4.9.0-1
- [x] `gh` v2.9.0-1
- [x] `git-lfs` v3.1.4-1
- [x] `glide` v0.13.3-15
- [x] `go-md2man` v2.0.2-1
- [x] `go` v1.19.4+tools0.4.0+net0.4.0
- [x] `gogs` v0.12.6-1
- [x] `gost` v2.11.4
- [x] `gotop` v4.1.3-1
- [x] `graftcp` v0.4.0-1
- [x] `hub` v2.14.2+git20220404-1
- [x] `hugo` v0.99.0-2
- [x] `idnkit` v2.3
- [x] `inetutils` v2.4
- [x] `iproute2` v6.0.0
- [x] `iptables` v1.8.8
- [x] `iw` v5.19
- [x] `kcptun` v20210922-1
- [x] `keybase` v5.9.3-1
- [x] `libbpf` v1.0.1
- [x] `libguestfs` v1.48.6
- [x] `mongodb` v4.4.14-1
- [x] `mtr` v0.95
- [x] `net-tools` v2.10
- [x] `netcat` v1.219
- [x] `nfs-utils` v2.6.2
- [x] `nghttp2` v1.51.0
- [x] `obfs4proxy` v0.0.11-14
- [x] `openssh` v9.1p1
- [x] `pcstat` v0.0.1-1
- [x] `podman` v4.0.3-2
- [x] `popub` v0+git20210814-1
- [x] `proton-bridge` v2.1.3-2
- [x] `pup` v0.4.0+git20220307-1
- [x] `rclone` v1.58.1-2
- [x] `restic` v0.13.1-1
- [x] `rsync` v3.2.7
- [x] `syncthing` v1.22.2
- [x] `v2ray-plugin` v1.3.1-6
- [x] `v2ray` v5.1.0
- [x] `wpa-supplicant` v2.10
- [x] `xray` v1.6.6

Security Update?
----------------

No

Build Order
-----------

```
iptables iproute2 inetutils bluez libbpf bcc bpftrace nghttp2 arp-scan go groups/go-rebuilds clash dnsmasq ethtool idnkit bind iw mtr net-tools netcat openssh rsync v2ray wpa-supplicant nfs-utils
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by Cyanoxygen** [comment]
Testing
--------
Here are the test results for every updated package in this survey.
Each application is manually run.

**Comment by Cyanoxygen** [comment]
android-platform-tools
--------
Works fine (with wireless ADB):
image

arp-scan
--------
Works fine:
image

**Comment by Cyanoxygen** [comment]
bind
--------
Works fine:
image
image

bluez
--------
Works fine, but I don't have a Bluetooth device:
image

clash
--------
It runs (I don't have any Clash configuration):
image

dnsmasq
--------
Works fine:
image
image

**Comment by Cyanoxygen** [comment]
ethtool
--------
Works fine:
image

idnkit
---------
Works fine:
image
Emojis are not allowed in domain names.
image

inetutils
--------
Works fine:
image

iproute2
--------
Works fine:
image
image
image

iptables
--------
It runs (have zero knowledge of this):
image

iw
--------
It runs (do not have wireless hardware):
image

mtr (failed)
--------
mtr is not able to run (missing asan shared library)
--------
image

**Comment by Cyanoxygen** [comment]
mtr
--------
Works fine (after rebuild):
image

net-tools
--------
arp is missing (Are they removed this command?).

**Comment by Cyanoxygen** [comment]
@Cyanoxygen It seems like some commands are not being built with default Makefile.

**Comment by Cyanoxygen** [comment]
net-tools
--------
All programs supposed to exist are present.
image
image
image
image

**Comment by Cyanoxygen** [comment]
nc
--------
Works fine:
image
image

nfs-utils
--------
Works fine:
image
image
image
image

nghttp2:
-------
Works fine. It is an HTTP/2 client, it needs to access HTTP/2-enabled websites (such as Cloudflare):
image

openssh
--------
Works fine (this test machine is accessed through SSH):
image

**Comment by Cyanoxygen** [comment]
rsync
--------
Works fine:
image

v2ray
--------
It runs (I do not have any v2ray server):
image

wpa-supplicant
--------
It runs:
image

**Review by Cyanoxygen — DISMISSED** [review]

**Review by Cyanoxygen — DISMISSED** [review]

**Review by Cyanoxygen — DISMISSED** [review]

**Review by Cyanoxygen — DISMISSED** [review]

**Review by liushuyu — APPROVED** [review]

**Pull request merged**
