### PR TITLE
linux-kernel: update to 6.10.12

### PR DESCRIPTION
**Pull request by KexyBiscuit**
Topic Description
-----------------

- kernel-tools: update to 6.10.12
    - Synchronized patches from linux-kernel.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel: update to 6.10.12
    - Update LoongArch Xe patch.
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.10.12, current HEAD is ac13a4261d6ee3891247618c75a73cac1d7727a6.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- kernel-tools: update to 6.10.12-rc1a
    - Synchronize patches from linux-kernel.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel: update to 6.10.12-rc1a
    - Remove LoongArch specific patches from other architectures.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- kernel-tools: update to 6.10.12-rc1
    - Synchronized patches from linux-kernel.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux+kernel: update to 6.10.12
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel: update to 6.10.12-rc1
    - Routine patch due diligence for stable releases.
    - Now following contribution guidelines of Android common kernels <https://android.googlesource.com/kernel/common/+/refs/heads/android-mainline/README.md>.
    - Backport tags from branch linux-kernel-6.11.0.
    - Dropped MIPS patches.
    - Add more video related patches from Huacai Chen.
    - Applied as many patches as possible to all architectures.
    - Updated yt6801 patches from deepin.
    - Updated patch from kernel_compiler_patch.
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.10.12, current HEAD is 977406ec8e1271bf3a986ea6fead9130186c2829.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>

Package(s) Affected
-------------------

- kernel-tools: 6.10.12-1
- linux+kernel: 3:6.10.12
- linux-kernel-${__VER}: 1:6.10.12-1

Security Update?
----------------

No

Build Order
-----------

```
#buildit linux-kernel linux+kernel kernel-tools
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 generation 2, AMD64 generation 1 and Armv8-A generation 2 Hyper-V VMs.

image
image
image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 VMware VM.

- Product: VMware® Workstation 17 Pro
- Version: 17.6.0 build-24238078
- Host OS version: Windows 11 Enterprise, 64-bit (Build 27695.1000) 10.0.27695
- Accelerate 3D graphics: on
- Firmware type: UEFI
- Host VBS Mode: on

image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on 战神Z8-KP7S2.

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on RedmiBook 16 (锐龙版).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Surface Pro (5th Gen).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on ROG Ally (2023).

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on ProArt B550-CREATOR.

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Latitude D630.

图片

**Comment by MingcongBai** [comment]
Smoke test passed on LoongArch (THTF Chaorui L860-T2, 3A5000M).

**Review by MingcongBai — APPROVED** [review]

**Pull request merged**
