### PR TITLE
osu-lazer: update to 2020.1114.0

### PR DESCRIPTION
**Pull request by OriginCode**
Topic Description
-----------------

Update osu-lazer to 2020.1114.0
Change dotnet publish with `--self-contained` to `--no-self-contained`

dotnet --self-contained:
> Publishes the .NET runtime with your application so the runtime doesn't need to be installed on the target machine. Default is true if a runtime identifier is specified and the project is an executable project (not a library project). For more information, see .NET application publishing and Publish .NET apps with the .NET CLI.

Package(s) Affected
-------------------

osu-lazer

Security Update?
----------------

No

Architectural Progress
----------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

### CODE REVIEW

**Comment by OriginCode** [comment]
Test on amd64:
1. Failed due to our dotnet runtime path is not `/usr/share/dotnet` but `/usr/lib/dotnet`
2. No sound, error: (Reboot and solved)
~~`ALSA lib /var/cache/acbs/build/acbs.43ky3hbx/alsa-lib-1.2.1.2/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such device`~~

Workaround:
1. set env `DOTNET_ROOT=/usr/lib/dotnet`
~~2. WIP~~

image

**Comment by OriginCode** [comment]
LGTM
image

**Review by MingcongBai — APPROVED** [review]

**Comment by MingcongBai** [comment]
@eatradish @Cyanoxygen Did you get a chance to test this out on `arm64`?

@OriginCode Please hold off from merging this PR before we are sure that it works (or not) on `arm64`.

**Comment by MingcongBai** [comment]
Converted to draft to prevent merging.

**Pull request closed without merging**
