### PR TITLE
PKGDES spell check

### PR DESCRIPTION
**Pull request by gumblex**
* Capitalize all sentences
* Quick check for common mistakes

### CODE REVIEW

**Comment by MingcongBai** [comment]
Merging later next week for July wave.

**Comment by LionNatsu** [comment]
Ping~

**Comment by MingcongBai** [comment]
@LionNatsu 七月塞不下

**Comment by l2dy** [comment]
conflicts...

**Comment by gumblex** [comment]
If you are going to merge it, revert the "bump REL" commit and run this https://gist.github.com/gumblex/d8ac485437181c485d4e94b46aafd193 to bump RELs.
(using https://github.com/AOSC-Dev/abbs-meta/blob/master/tools/increaserel.py)

**Comment by l2dy** [comment]
@gumblex Still conflicts...

**Comment by l2dy** [comment]
@gumblex @MingcongBai OK to merge?

**Comment by MingcongBai** [comment]
Looks good to me. Fire away!

**Pull request merged**
