### PR TITLE
atm: new, 0.1.4

### PR DESCRIPTION
**Pull request by MingcongBai**
Topic Description
-----------------

Introduce [ATM](/AOSC-Dev/atm), and add it to `admin-base` so that it will be installed with an update.

Package(s) Affected
-------------------

- `atm` v0.1.4
- `admin-base` v7

Security Update?
----------------

- [ ] Yes
- [x] No

Architectural Progress
----------------------

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

### CODE REVIEW

**Review by liushuyu — APPROVED** [review]

**Comment by MingcongBai** [comment]
Guys, please help out testing this package by **prepending** the following...

```
deb https://repo.aosc.io/debs atm-0.1.4-new main
```

Before everything in your `/etc/apt/sources.list`. Thanks!

**Comment by MingcongBai** [comment]
Runtime error on `loongson3`:

```
root@loongson3-20002 [ ~ ] # atm
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.15.0/src/cursive_ext.rs:68:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Segmentation fault (core dumped)
```

@liushuyu Should I attempt a build without LTO or Clang?

**Review by OriginCode — APPROVED** [review]
LGTM on amd64 arch.

**Comment by MingcongBai** [comment]
Will skip `loongson3` for now, it does not build. `v0.1.5` fixes the segfault with an alternative terminal library.

**Comment by MingcongBai** [comment]
Post-Merge Architectural Progress
----------------------



- [x] AMD64 `amd64`
- [x] AArch64 `arm64`






Post-Merge Secondary Architectural Progress
--------------------------------



Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

**Pull request merged**
