### PR TITLE
lychee: update to 0.14.0

### PR DESCRIPTION
**Pull request by eatradish**
Topic Description
-----------------

- lychee: update to 0.14.0

Package(s) Affected
-------------------

- lychee: 0.14.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit lychee
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by eatradish** [comment]
LGTM on AMD64

图片

**Review by MingcongBai — DISMISSED** [review]

**Comment by eatradish** [comment]
@aosc-buildit-bot build ppc64el,loongson3,riscv64,mips64r6el

**Comment by eatradish** [comment]
@aosc-buildit-bot build loongson3,mips64r6el

**Comment by eatradish** [comment]
@aosc-buildit-bot build ppc64el,loongson3,riscv64,mips64r6el

**Review by MingcongBai — APPROVED** [review]

**Comment by eatradish** [comment]
@aosc-buildit-bot build

**Pull request merged**
