### PR TITLE
rustc: update to 1.48.0

### PR DESCRIPTION
**Pull request by liushuyu**
Topic Description
-----------------

Update Rust compiler to 1.48.0: https://blog.rust-lang.org/2020/11/19/Rust-1.48.html

Package(s) Affected
-------------------

- `rustc`

Security Update?
----------------

No

Architectural Progress
----------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

---
This change is [Reviewable](https://reviewable.io/reviews/aosc-dev/aosc-os-abbs/2547)

### CODE REVIEW

**Comment by liushuyu** [comment]
Rebuild listing:

```
extra-admin/atm
extra-admin/ytop
extra-devel/sccache
extra-devel/tokei
extra-doc/tealdeer
extra-editors/neovim-gtk
extra-gnome/fractal
extra-i18n/ydcv-rs
extra-java/icedtea-web
extra-libs/js-68
extra-libs/js-78
extra-libs/librsvg
extra-multimedia/netease-cloud-music-gtk
extra-network/shadowsocks-rust
extra-phosh/squeekboard
extra-python/rustpython
extra-rust/cargo-audit
extra-rust/racer
extra-utils/alacritty
extra-utils/autojump-rs
extra-utils/bat
extra-utils/exa
extra-utils/fd
extra-utils/mcfly
extra-utils/nix-user-chroot
extra-utils/ripgrep
extra-web/firefox
extra-web/seamonkey
extra-web/thunderbird
extra-web/zola
extra-wm/way-cooler
extra-wm/way-cooler-bg
extra-wm/way-cooler-grab
extra-wm/way-cooler-lock
```

**Comment by liushuyu** [comment]
Note: requires `autobuild3` with version `>=20201124` to build.

**Comment by MingcongBai** [comment]
@liushuyu Please wait for Core 8 for build testing and merging.

**Comment by liushuyu** [comment]
Superseded by #2635.

**Pull request closed without merging**
