### PR TITLE
linux-kernel-lts (Linux Kernel, Longterm): update to 6.6.48

### PR DESCRIPTION
**Pull request by MingcongBai**
Topic Description
-----------------

- linux+kernel+lts: update to 6.6.48
- linux-kernel-lts: update to 6.6.48
    - Use __VER to remove hard-coded versioning in autobuild/defines.
    - Refresh patches at AOSC-Tracking/linux @ aosc/v6.6.48,
    HEAD: 0439dfdb184bd8d995fb4bb629eb90db428cae9a.
    - Disable CONFIG_FB_HYPERV in favour of hyperv_drm (CONFIG_DRM_HYPERV).

Package(s) Affected
-------------------

- linux+kernel+lts: 2:6.6.47
- linux-kernel-lts-${__VER}: 6.6.48

Security Update?
----------------

No

Build Order
-----------

```
#buildit linux-kernel-lts linux+kernel+lts
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by hanyuwei70** [comment]
loong64 (3A6000) with rx550 not good, flashing green bar.
aarch64 good (d2000).

**Comment by MingcongBai** [comment]
> loong64 (3A6000) with rx550 not good, flashing green bar. aarch64 good (d2000).

Could not reproduce the green bar issue on my 3A5000 with WX 3100.

**Comment by KexyBiscuit** [comment]
To be superseded by #7907...

**Comment by KexyBiscuit** [comment]
Merged into #7907, closing.

**Pull request closed without merging**
