### PR TITLE
awesomewm family: drop, orphaned

### PR DESCRIPTION
**Pull request by OriginCode**
Topic Description
-----------------

- vicious: drop, orphaned
    Signed-off-by: Kaiyang Wu <origincode@aosc.io>
- awesome-network-manager: drop, orphaned
    Signed-off-by: Kaiyang Wu <origincode@aosc.io>
- awesome: drop, orphaned
    Signed-off-by: Kaiyang Wu <origincode@aosc.io>

Package(s) Affected
-------------------

Security Update?
----------------

No

Build Order
-----------

```
#buildit 
```

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`
- [ ] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by chenx97** [comment]
What's wrong with srm?

**Comment by OriginCode** [comment]
> What's wrong with srm?

Its sole reverse dependency is awesome-network-manager

**Comment by chenx97** [comment]
> > What's wrong with srm?
> 
> Its sole reverse dependency is awesome-network-manager

So if you delete awesome, it won't have reverse dependencies anymore, just like most apps out there lol

**Comment by MingcongBai** [comment]
> > What's wrong with srm?
> 
> Its sole reverse dependency is awesome-network-manager

Let's keep `srm` since it could be useful as a utility (and why was it a dependency in the first place?).

**Comment by OriginCode** [comment]
> > > What's wrong with srm?
> > 
> > 
> > Its sole reverse dependency is awesome-network-manager
> 
> Let's keep `srm` since it could be useful as a utility (and why was it a dependency in the first place?).

Dropped the commit, sir.

**Review by MingcongBai — APPROVED** [review]

**Pull request merged**
