### PR TITLE
abseil-cpp: update to 20240116.2 (rework again and again)

### PR DESCRIPTION
**Pull request by BC204**
Topic Description
-----------------

- mlt: bump REL due to movit rework
- movit:  disable parallel building for ppc64el and riscv64
- movit: fix profiling when running mlt
- digikam: [MIPS64R6EL] fix cannot find Qt5WebEngineWidgets_DIR

Package(s) Affected
-------------------

- digikam: 7.9.0-6
- mlt: 7.22.0-2
- movit: 1.7.1

Security Update?
----------------

No

Build Order
-----------

```
#buildit digikam movit mlt
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [x] MIPS R6 64-bit (Little Endian) `mips64r6el`

### CODE REVIEW

**Comment by BC204** [comment]
Waiting for kcalendarcore: ppc64el ...

**Comment by BC204** [comment]
Test mlt: 7.22.0 (stable) on amd64. Something may be wrong.
mlt-7 22 0

[mlt.txt](https://github.com/user-attachments/files/15816041/mlt.txt)

**Comment by MingcongBai** [comment]
> Test mlt: 7.22.0 (stable) on amd64. Something may be wrong. mlt-7 22 0
> 
> [mlt.txt](https://github.com/user-attachments/files/15816041/mlt.txt)

`mlt` might have had some profiling-related options enabled.

**Comment by BC204** [comment]
Test on amd64
digikam-7 9 0-6
mlt-fixed
mlt-7 22 0-2

**Review by jiegec — APPROVED** [review]

**Pull request merged**
