### PR TITLE
libvpl: update to 2.14.0

### PR DESCRIPTION
**Pull request by OriginCode**
Topic Description
-----------------

- vpl-gpu-rt: new, 24.4.4
    Signed-off-by: Kaiyang Wu <origincode@aosc.io>
- libvpl: update to 2.14.0
    Co-authored-by: Kaiyang Wu (@OriginCode) <self@origincode.me>
- libvpl-tools: new, 1.3.0
    Signed-off-by: Kaiyang Wu <origincode@aosc.io>
- ffmpeg: switch from Intel Media SDK to libVPL as recommended by Intel
    Signed-off-by: Kaiyang Wu <origincode@aosc.io>

Package(s) Affected
-------------------

- vpl-gpu-rt: 24.4.4
- libvpl: 2.14.0
- libvpl-tools: 1.3.0
- ffmpeg: 7.1-4

Security Update?
----------------

No

Build Order
-----------

```
#buildit vpl-gpu-rt libvpl libvpl-tools ffmpeg
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`

### CODE REVIEW

**Comment by OriginCode** [comment]
LGTM on amd64 (tested with obs-studio).

**Comment by OriginCode** [comment]
We might switch to libvpl for ffmpeg and orphan intel-media-sdk according to https://www.intel.com/content/www/us/en/developer/articles/technical/onevpl-in-ffmpeg-for-great-streaming-on-intel-gpus.html

**Comment by OriginCode** [comment]
ffmpeg (with libVPL) LGTM on amd64
圖片

**Comment by MingcongBai** [comment]
Hardware acceleration did not work on my 11th Gen laptop:

```
[ffmpeg] AVHWDeviceContext: Failed to initialise VAAPI connection: -1 (unknown libva error).
[ffmpeg/video] vp9_v4l2m2m: Could not find a valid device
[ffmpeg/video] vp9_v4l2m2m: can't configure decoder
```

Whereas before the update:

```
Using hardware decoding (vaapi).
```

**Review by MingcongBai — APPROVED** [review]
Tested good on my Panasonic Let's Note CF-SV2 (11th Gen, Tiger Lake).

**Pull request merged**
