### PR TITLE
workflows-lgtm: move if logic outside script

### PR DESCRIPTION
**Pull request by KexyBiscuit**

### CODE REVIEW

**Comment by KexyBiscuit** [comment]
Smoke test passed.

**Review by outloudvi — APPROVED** [review]
It's okay if smoke tests is passing. But as said by [GitHub docs](https://docs.github.com/en/actions/learn-github-actions/expressions):

> When you use expressions in an if conditional, you may omit the expression syntax (${{ }})

Well, I would really like to see it even easier to read over a style fix, actually...

**Comment by KexyBiscuit** [comment]
@outloudvi Removing `${{}}` results in a corrupted YAML file. GitHub tolerates that, but Visual Studio Code doesn't.

**Comment by outloudvi** [comment]
> @outloudvi Removing `${{}}` results in a corrupted YAML file. GitHub tolerate that, but Visual Studio Code doesn't.

Oh heck... 😅

**Pull request merged**
