### PR TITLE
ast-grep: update to 0.16.1

### PR DESCRIPTION
**Pull request by eatradish**
Topic Description
-----------------

- ast-grep: update to 0.16.1

Package(s) Affected
-------------------

- ast-grep: 0.16.1

Security Update?
----------------

No

Build Order
-----------

```
#buildit ast-grep
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by eatradish** [comment]
@aosc-buildit-bot build

**Comment by eatradish** [comment]
@aosc-buildit-bot build

**Review by MingcongBai — APPROVED** [review]

**Comment by eatradish** [comment]
LGTM on AMD64:

图片

**Comment by eatradish** [comment]
@aosc-buildit-bot build

**Pull request merged**
