### PR TITLE
protontricks: new, 1.9.2

### PR DESCRIPTION
**Pull request by OriginCode**
Topic Description
-----------------

Introduce new package "protontricks" and its dependency "vdf"

Package(s) Affected
-------------------

`protontricks` v1.9.2
`vdf` v3.4

Security Update?
----------------

No

Build Order
-----------

`vdf -> protontricks`

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] Architecture-independent `noarch`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] Architecture-independent `noarch`

### CODE REVIEW

**Comment by OriginCode** [comment]
Protontricks FTBFS
圖片

**Comment by MingcongBai** [comment]
@OriginCode This is due to Autobuild3 missing a few dependencies, namely python-build and python-installer.

**Comment by OriginCode** [comment]
LGTM, the version is (unknown), investigating.
圖片

**Comment by MingcongBai** [comment]
Stalled, @OriginCode will re-open a topic later. Closing.

**Pull request closed without merging**
