### PR TITLE
Snap[d]!

### PR DESCRIPTION
**Pull request by RedL0tus**
Packaging:
  - [ ] Make it build.
    - [x] Build without custom flags
    - [ ] Custom flags (help needed)

Make it work.
  - [x] "classical" snaps
  - [ ] "modern" snaps (help needed)

Misc:
  - [ ] AppArmor, currently disabled (emmm, discussion-needed)

Yet another Golang package...

### CODE REVIEW

**Comment by liushuyu** [comment]
> AppArmor, currently disabled (emmm, discussion-needed)

This thing AFAIK it's another variant of SELinux like mechanism...
Obviously, it's not going to be enabled by default.

**Comment by RedL0tus** [comment]
> > AppArmor, currently disabled (emmm, discussion-needed)
> 
> This thing AFAIK it's another variant of SELinux like mechanism...
> Obviously, it's not going to be enabled by default.

I know... maybe Just make it optional...
In this case, AppArmor is used to prevent programs inside containers ("snaps") access files outside the containers.
Without it, snapd will run all snaps in "development mode", without that "protection".

**Comment by liushuyu** [comment]
>In this case, AppArmor is used to prevent programs inside containers ("snaps") access files outside the containers.


`AppArmor` is a sandbox controller, configuring this thing correctly is a total hassle.

**Comment by RedL0tus** [comment]
> > In this case, AppArmor is used to prevent programs inside containers ("snaps") access files outside the containers.
> 
> `AppArmor` is a sandbox controller, configuring this thing correctly is a total hassle.

According to Arch wiki, it seems it does not require much configuration in this specific case, and snapd can generate AppArmor rules for each snap.

**Comment by MingcongBai** [comment]
Closing - this is *not* a rejection.

We are switching to a topic-based maintenance system. Please re-create your PR against our `stable` branch, use our new Pull Request template, and work in accordance to our [maintenance guidelines](https://wiki.aosc.io/developer/packaging/topic-based-maintenance-guideline/).

**Pull request closed without merging**
