### PR TITLE
linux-kernel: update to 6.11.8

### PR DESCRIPTION
**Pull request by KexyBiscuit**
Topic Description
-----------------

- linux-kernel: update Armv8-A AArch64 config for SAM patch
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel: update config for Surface Pro (5th Generation – 1796)
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- kernel-tools: synchronize patches from linux-kernel
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel: add selected patches from linux-surface
    - Currently targeting Surface Pro (5th Generation – 1796).
    - Also backport Surface Aggregator Module thermal sensor driver from upstream.
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.11.8, current HEAD is 3a85a395f299b89ae0d93da136a3a1de8a1c7379.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux+kernel: update to 6.11.8
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel: update config for 6.11.8
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- kernel-tools: update to 6.11.8
    - Synchronize patches from linux-kernel.
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel: update to 6.11.8
    - Routine patch due diligence for upstream releases.
    - Now following contribution guidelines of Android common kernels <https://android.googlesource.com/kernel/common/+/refs/heads/android-mainline/README.md>.
    - Update EDAC patches for LoongArch.
    - Update patch for hardware video decoding on GCN AMD GPUs.
    - Add patch for DWMAC on Phytium Tengrui D2000.
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.11.8, current HEAD is d40ebe11cb34f927eab4f0d6b6c21dc1e029e60b
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel: update 64-bit RISC-V config for 6.11.7
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>
- linux-kernel: update AMD64 config for 6.11.7
    Signed-off-by: Kexy Biscuit <kexybiscuit@aosc.io>

... and 3 more commits

Package(s) Affected
-------------------

- kernel-tools: 6.11.8-2
- linux+kernel: 3:6.11.8
- linux-kernel-${__VER}: 1:6.11.8-2

Security Update?
----------------

No

Build Order
-----------

```
#buildit linux-kernel linux+kernel kernel-tools
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 VMware VM.

- Product: VMware® Workstation 17 Pro
- Version: 17.6.1 build-24319023
- Host OS version: Windows 11 Enterprise, 64-bit (Build 27749.1000) 10.0.27749
- Accelerate 3D graphics: on
- Firmware type: UEFI
- Host VBS Mode: on

image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 generation 2, AMD64 generation 1 and Armv8-A generation 2 Hyper-V VMs.

image
image
image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on XA612A0.

图片

**Comment by MingcongBai** [comment]
Tested good:

- Loongson XA61200
- THTF Chaorui T860-G2

**Review by MingcongBai — APPROVED** [review]

**Pull request merged**
