### PR TITLE
Autobuild4 4.0.2

### PR DESCRIPTION
**Pull request by liushuyu**
Topic Description
-----------------

- autobuild4: new, 4.0.0

Package(s) Affected
-------------------

- autobuild4: 4.0.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit autobuild3 autobuild4
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`

**Second Architectures**

- [x] Loongson 3 `loongson3`
- [x] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by eatradish** [comment]
@aosc-buildit-bot build

**Comment by eatradish** [comment]
@aosc-buildit-bot build

**Comment by liushuyu** [comment]
@aosc-buildit-bot build

**Comment by liushuyu** [comment]
@aosc-buildit-bot build

**Review by MingcongBai — APPROVED** [review]

**Pull request merged**
