### PR TITLE
cinepaint: drop, upstream no longer maintained

### PR DESCRIPTION
**Pull request by jiegec**
Topic Description
-----------------

- nufraw: bump REL due to cinepaint removal, fix FTBFS
- cinepaint: drop, upstream no longer maintained

Package(s) Affected
-------------------

- nufraw: 0.43+3-2

Security Update?
----------------

No

Build Order
-----------

```
#buildit nufraw
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

### CODE REVIEW

**Comment by jiegec** [comment]
No linux sources available: https://sourceforge.net/projects/cinepaint/files/CinePaint/

**Comment by MingcongBai** [comment]
Please also drop cinepaint from nufraw's build dependency.

**Comment by jiegec** [comment]
> Please also drop cinepaint from nufraw's build dependency.

nufraw does not build either..

**Comment by jiegec** [comment]
> Please also drop cinepaint from nufraw's build dependency.

Fixed

**Review by MingcongBai — APPROVED** [review]

**Pull request merged**
