### PR TITLE
git: bump to 2.6.0

### PR DESCRIPTION
**Pull request by lmy441900**
Update Git

### CODE REVIEW

**Comment by lmy441900** [comment]
I haven't built it and pushed it to the repository yet.

**Comment by Icenowy** [comment]
Plz try to build. You can use twbot to testit

**Comment by MingcongBai** [comment]
It builds. Merging.

**Comment by Icenowy** [comment]
标准难道不是works吗。。。

**Comment by MingcongBai** [comment]
你觉得这种东西不 work 我不会发现么……

**Pull request merged**
