### PR TITLE
firefox: update to 84.0.1

### PR DESCRIPTION
**Pull request by szclsya**
Topic Description
-----------------
Update Firefox to 84.0.1

Package(s) Affected
-------------------
- firefox
- nss

Security Update?
----------------
No

Build Order
-----------
nss -> firefox

Architectural Progress
----------------------
- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------
Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------
- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------
Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

### CODE REVIEW

**Comment by szclsya** [comment]
image

Works as intended on `AMD64`.

**Review by MingcongBai — APPROVED** [review]

**Comment by MingcongBai** [comment]
Why did you strike out POWER?

**Comment by szclsya** [comment]
Sorry, supposed to strike out Loongson 3. Fixed now.

**Comment by MingcongBai** [comment]
@szclsya No worries.

**Pull request merged**
