### PR TITLE
xf86-video-siliconmotion:new, 1.7.9

### PR DESCRIPTION
**Pull request by FlyGoat**
X.Org driver for siliconmotion. Required by some Loongson Lemote devices.

### CODE REVIEW

**Comment by MingcongBai** [comment]
Interesting, I was going to do it this weekend. Does this snapshot contain the patch from Anheng that fixes memory address issue on 8089?

**Comment by FlyGoat** [comment]
No,because anheng have no patchs for current 1.7.9.
I'm trying to port it.
(Complie on Loonson device really spend a lot of time...

**Comment by MingcongBai** [comment]
Seems like the patch applies just fine.

**Comment by FlyGoat** [comment]
It coulde be applied but cause a complie error.

**Comment by MingcongBai** [comment]
I see, shall I leave that to you then? 1.7.9 simply will not work on a 8089 without their patch.

**Comment by FlyGoat** [comment]
That's ok.

**Comment by MingcongBai** [comment]
Sorry about that, I'm just kind of overloaded at the moment.

**Comment by FlyGoat** [comment]
Done, finally it works.
Shall I patch pixman to support loongson-simd soon?

**Comment by MingcongBai** [comment]
> Done, finally it works.

Congrats, mind providing a copy of your Xorg.0.log? Also are you testing on AOSC OS or other distro - I have just pushed a kernel for MIPS32, you may install `linux-kernel-4.9.12` to test it out...

> Shall I patch pixman to support loongson-simd soon?

I would be cautious with that... Will this break compatibility with other MIPS devices?

**Comment by MingcongBai** [comment]
If it does, we could start providing "BSP" style packages for Lemote devices for optimisation purposes.

**Comment by FlyGoat** [comment]
I've tried on Lynloong by a ramfs busybox test environment (AOSC does not provide a bootable image) so I can't provide a log for now.... 
I'm still studying on that patch. Maybe it does.

**Comment by MingcongBai** [comment]
For installation of AOSC on a 8089, please come over to #aosc on IRC or our Telegram group. I can help step by step.

**Comment by FlyGoat** [comment]
I've joined telegram group but I have no 8089. I just have a Lynloong(as known as 9003) witch retired from my school.

**Comment by FlyGoat** [comment]
A lot of patch work would be required to make it run Mainline kernel.

**Comment by FlyGoat** [comment]
You can merge this PR form now. All wioks belong to this PR are done.

**Comment by MingcongBai** [comment]
Nope, 2E/F machine's are supported by the mainline.

2017年3月3日 13:38，"Jiaxun Yang" <notifications@github.com>写道：

**Comment by MingcongBai** [comment]
> You can merge this PR for now. All wioks belong to this PR are done.

Thank you very much mate!

**Pull request merged**
