### PR TITLE
json-c: update to 0.16.0

### PR DESCRIPTION
**Pull request by eatradish**
Topic Description
-----------------

json-c: update to 0.16.0

Package(s) Affected
-------------------

json-c: update to 0.16.0
json-c-rebuilds

Security Update?
----------------

No

Build Order
-----------

json-c stfl libwebsockets groups/json-c-rebuilds

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by eatradish** [comment]
stfl FTBFS in loongson3:

```
cd python && python -c 'import stfl'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "stfl.py", line 15, in <module>
    import _stfl
ImportError: dynamic module does not define init function (init_stfl)
```

**Comment by MingcongBai** [comment]
> stfl FTBFS in loongson3:
> 
> ```
> cd python && python -c 'import stfl'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "stfl.py", line 15, in <module>
>     import _stfl
> ImportError: dynamic module does not define init function (init_stfl)
> ```

@liushuyu @FlyGoat Your input are appreciated.

**Review by MingcongBai — CHANGES_REQUESTED** [review]
Please revise your commits for `libu2f-host`, `libu2f-server`, and `yubikey-personalization`. Follow our commit msg convention:

```
libu2f-host: (whose patch?) ...

- Explain in detail what it fixes.

Ref: ...
```

**Comment by FlyGoat** [comment]
Looks like lacks arch specific function. @eatradish Perhaps pick some body in office to look into the issue? They need this kind of practice.

Thanks

**Review by MingcongBai — DISMISSED** [review]

**Comment by MingcongBai** [comment]
Deferring rebuild for `loongson3`, since it's a secondary architecture.

**Review by MingcongBai — APPROVED** [review]

**Pull request merged**
