### PR TITLE
libvirt Survey (March, 2024)

### PR DESCRIPTION
**Pull request by MingcongBai**
Topic Description
-----------------

- virt-manager: update LoongArch patch set
    Ref: https://github.com/lixianglai/virt-manager @ loongarch
- libvirt-python: update to 10.1.0
- libvirt-glib: update to 5.0.0
- libvirt: update to 10.2.0
    This version adds LoongArch guest support. Drop all upstreamed patches.
- wireshark: rebuild to correct library path
    - With Autobuild4 >= 4.0.24 & <= 4.0.26, the CMAKE_INSTALL_LIBDIR was assigned
    an incorrect value, causing its library path to be recorded as /usr/usr/lib.
    - This rebuild corrects this issue.

Package(s) Affected
-------------------

- libvirt-glib: 5.0.0
- libvirt-python: 10.1.0
- libvirt: 10.2.0
- virt-install: 4.1.0-3
- virt-manager: 4.1.0-3
- wireshark: 4.2.3-1

Security Update?
----------------

No

Build Order
-----------

```
#buildit wireshark libvirt libvirt-glib libvirt-python virt-manager
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

**Experimental Architectures**

- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`

### CODE REVIEW

**Comment by MingcongBai** [comment]
After updating QEMU to 8.2.2, virt-manager seems to be having a hard time recognising `loongarch64` CPU models.

**Comment by jiegec** [comment]
Ready for review?

**Comment by MingcongBai** [comment]
> Ready for review?

No, not yet. Qemu 8.2.2 seems to have broken virt-manager somehow.

Also, libvirt 10.2.0 was released with upstream support for LoongArch. I have just included that update to re-test.

**Comment by MingcongBai** [comment]
I could not get `virt-manager` to detect LoongArch UEFI images.

**Comment by jiegec** [comment]
Please bring libvirt loongarch patches back and try again.

**Comment by jiegec** [comment]
qemu 9.0.0 is out

**Review by jiegec — APPROVED** [review]
Launch loongarchlinux vm on loongarch64 successfully.

**Comment by jiegec** [comment]
image

**Pull request merged**
