### PR TITLE
Add .editorconfig.

### PR DESCRIPTION
**Pull request by KexyBiscuit**
## See also

[EditorConfig](https://editorconfig.org/)

### CODE REVIEW

**Comment by MingcongBai** [comment]
Looks good to me... @cthbleachbit What do you think?

**Review by cthbleachbit — APPROVED** [review]

**Comment by cthbleachbit** [comment]
Oh wait, all patches and diffs shall be free from such constraints

**Review by cthbleachbit — CHANGES_REQUESTED** [review]
Please exclude all `[*.patch]` and `[*.diff]` from editor config as these files must be kept verbatim for patch to work.

**Comment by KexyBiscuit** [comment]
> Please exclude all `[*.patch]` and `[*.diff]` from editor config as these files must be kept verbatim for patch to work.

Resolved.

**Comment by MingcongBai** [comment]
@cthbleachbit Could you update your review status?

**Review by MingcongBai — APPROVED** [review]

**Pull request merged**
