### PR TITLE
flat-plat: import, 3.20.20160404

### PR DESCRIPTION
**Pull request by lmy441900**
w/o GDM themes and Chrome extensions.

### CODE REVIEW

**Comment by MingcongBai** [comment]
Would you mind helping my OCD by capitalizing the first letter in `PKGDES`. And no, if it's plainly a theme (a.k.a. a data package), there would be no `PKGDEP` in this case, as the theme does not contain any `.so` like older GTK+ themes.

**Comment by lmy441900** [comment]
> Would you mind helping my OCD by capitalizing the first letter in `PKGDES`. 
The old guideline of AOSC OS packages said so (you told me that). Anyway I'll fix that.

> if it's plainly a theme (a.k.a. a data package), there would be no `PKGDEP` in this case
:ok:

**Comment by MingcongBai** [comment]
> The old guideline of AOSC OS packages said so (you told me that). Anyway I'll fix that.

🤣 Let's just say I was stupid...

**Comment by MingcongBai** [comment]
Looks good, thanks!

**Pull request merged**
