### PR TITLE
git: update to 2.30.0

### PR DESCRIPTION
**Pull request by OriginCode**
Topic Description
-----------------

Update git to 2.30.0

Package(s) Affected
-------------------

git

Security Update?
----------------

No

Architectural Progress
----------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

### CODE REVIEW

**Comment by OriginCode** [comment]
LGTM on amd64:
image

**Review by cthbleachbit — APPROVED** [review]
Shell completion is working for me now. Both amd64 and arm64 tested.

**Review by cthbleachbit — CHANGES_REQUESTED** [review]
Wait a second.

**Comment by cthbleachbit** [comment]
Try to press tab after any git command:

1. go to a git repo
2. type `git checkout ` then press tab until completion appears
3. press C-c
4. bash would keep prompting `-bash: [: 1: unary operator expected`
5. this would keep occuring even you change directory out of this git repo.

See this recording: https://asciinema.org/a/DAacgq2N9iq8SltaDbEVR7tcp

**Comment by OriginCode** [comment]
@cthbleachbit Confirmed.

**Comment by OriginCode** [comment]
> Try to press tab after any git command:
> 
>     1. go to a git repo
> 
>     2. type `git checkout ` then press tab until completion appears
> 
>     3. press C-c
> 
>     4. bash would keep prompting `-bash: [: 1: unary operator expected`
> 
>     5. this would keep occuring even you change directory out of this git repo.
> 
> 
> See this recording: https://asciinema.org/a/DAacgq2N9iq8SltaDbEVR7tcp

It does not occur when the `bashrc` from Arch Linux is applied.
image

**Comment by MingcongBai** [comment]
@OriginCode Which would be irrelevant, since our Bash configuration provides a custom Git status prompt - found in /etc/bashrc.d.

**Comment by cthbleachbit** [comment]
> @OriginCode Which would be irrelevant, since our Bash configuration provides a custom Git status prompt - found in /etc/bashrc.d.

Sure. Go ahead approve and merge.

**Comment by cthbleachbit** [comment]
Or do you want to handle that in this PR as well?

**Comment by OriginCode** [comment]
@cthbleachbit cc @MingcongBai

**Comment by MingcongBai** [comment]
@cthbleachbit Obviously this will have to be addressed before Git 2.23 or we are breaking user experience by updating a package.

**Comment by MingcongBai** [comment]
Problem identified, will release an update to `bash-config` shortly. Stand by.

**Comment by MingcongBai** [comment]
@OriginCode Tagged v0.4.6.4 for `bash-config`, could you please help and build it?

**Comment by OriginCode** [comment]
@MingcongBai Received. Thanks for your help.

**Review by MingcongBai — APPROVED** [review]

**Review by cthbleachbit — APPROVED** [review]

**Pull request merged**
