### PR TITLE
FFmpeg: enable neon for arm64; 

### PR DESCRIPTION
**Pull request by xyq1113723547**
- Enable FFmpeg NEON support on arm64.
- armv8-a mandates to support NEON.

Topic Description
-----------------

FFmpeg: enable neon for arm64

Package(s) Affected
-------------------

Firefox, vlc, mpv, mplayer, x264 and possibly all packages depend on FFmpeg.

Security Update?
----------------

No

Test Build(s) Done
------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

### CODE REVIEW

**Comment by WhiredPlanck** [comment]
Just a suggestion: always keep the commit messages in lower case unless it's really needed to use upper case.

**Comment by MingcongBai** [comment]
@WhiredPlanck Not a suggestion, a requirement from the Styling Manual. Also, with us already specifying -march=armv8, and that FFmpeg already has runtime SIMD detection, why is this still necessary?

**Comment by WhiredPlanck** [comment]
> Not a suggestion, a requirement from the Styling Manual.

Oops, I almost forgot this. It may become my instinct. :P

**Comment by KexyBiscuit** [comment]
As @MingcongBai says, it's unnecessary to manually specify NEON support: it's enabled by default on AArch64[^1].

`configure` output on stable following.

```
install prefix            /usr
source path               .
C compiler                gcc
C library                 glibc
ARCH                      aarch64 (generic)
big-endian                no
runtime cpu detection     yes
NEON enabled              yes
VFP enabled               yes
debug symbols             no
strip symbols             no
optimize for size         no
optimizations             yes
static                    no
shared                    yes
postprocessing support    yes
network support           yes
threading support         pthreads
safe bitstream reader     yes
texi2html enabled         no
perl enabled              yes
pod2man enabled           yes
makeinfo enabled          yes
makeinfo supports HTML    yes
```

Pull request closing as invalid.

[^1]: https://github.com/FFmpeg/FFmpeg/blob/n4.2.5/configure#L5700

**Pull request closed without merging**
