### PR TITLE
john edb:import

### PR DESCRIPTION
**Pull request by liushuyu**
john: John The Ripper, original official version, no acceleration
edb: Evan's Debugger, QT5 version

### CODE REVIEW

**Comment by Arthur2e5** [comment]
john, edb: import

**Comment by liushuyu** [comment]
............................................

**Comment by liushuyu** [comment]
Key "," broke down

**Comment by MingcongBai** [comment]
`extra-security/john/autobuild/build` can you move this file to `extra-security/john/autobuild/amd64/build`? As it's architectural specific.

`extra-security/john/autobuild/prepare` the `-march=x86-64` bit is unnecessary.

**Comment by Arthur2e5** [comment]
We should pull-rebase this, and then perform our changes.

**Comment by liushuyu** [comment]
It's necessary... JTR contains assembly module ....
I will move this

**Comment by MingcongBai** [comment]
> We should pull-rebase this, and then perform our changes.

Let me finish up MATE first (preemptive uni-task).

**Comment by MingcongBai** [comment]
> It's necessary... JTR contains assembly module ....

Defined as part of autobuild3's `libarch` configuration, so no worries.

**Comment by liushuyu** [comment]
All right

**Comment by MingcongBai** [comment]
Please, use the `module: comment bla bla bla` format from now on... it will make our lives that much harder just reading through all sorts of commit format.

**Comment by liushuyu** [comment]
All right

**Comment by Arthur2e5** [comment]
Stop running your idiotic fixes... everything shall be rebased.

**Comment by Arthur2e5** [comment]
How did you ever manage to say those things were imported? NEW NEW NEW

**Comment by Arthur2e5** [comment]
Can you fscking look at the Qt procedures and stop writing your `build` things?

**Comment by MingcongBai** [comment]
> How did you ever manage to say those things were imported? NEW NEW NEW

Refer to CONTRIBUTING.md @liushuyu

**Comment by Arthur2e5** [comment]
From your usage of `*.desktop` plus `install`, I believe you are copying something like PKGBUILD.

**Comment by Arthur2e5** [comment]
Time to patch the Makefile. Whee!

**Pull request closed without merging**
