### PR TITLE
linux-kernel: update to 6.10.8

### PR DESCRIPTION
**Pull request by KexyBiscuit**
Topic Description
-----------------

- kernel-tools: update to 6.10.8
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.10.8, current HEAD is af27af370ff934cf39b889f2db3a7869cdd4f72c.
- linux+kernel: update to 6.10.8
- linux-kernel: update to 6.10.8
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.10.8, current HEAD is af27af370ff934cf39b889f2db3a7869cdd4f72c.
- kernel-build-common: enable objtool on amd64, loongarch64, ppc64el

Package(s) Affected
-------------------

- kernel-build-common: 13
- kernel-tools: 6.10.8
- linux+kernel: 3:6.10.8
- linux-kernel-${__VER}: 1:6.10.8

Security Update?
----------------

No

Build Order
-----------

```
#buildit kernel-build-common linux-kernel linux+kernel kernel-tools
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 VMware VM.

- Product: VMware® Workstation 17 Pro
- Version: 17.6.0 build-24238078
- Host OS version: Windows 11 Enterprise, 64-bit (Build 27695.1000) 10.0.27695
- Accelerate 3D graphics: on
- Firmware type: UEFI
- Host VBS Mode: on

image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 generation 2, AMD64 generation 1 and Armv8-A generation 2 Hyper-V VMs.

image
image
image

**Comment by OriginCode** [comment]
LGTM on amd64:
圖片

**Comment by OriginCode** [comment]
LGTM on loongarch64:
Screenshot_20240905_135948

**Review by OriginCode — APPROVED** [review]

**Pull request merged**
