### PR TITLE
linux-kernel: update to 6.10.10

### PR DESCRIPTION
**Pull request by KexyBiscuit**
Topic Description
-----------------

- kernel-tools: update to 6.10.10-rc1
    - Patch due diligence not done yet... Wanna sleep for now.
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.10.10-rc1, current HEAD is 89ccd25504a2dec38cd82833c7cb005a56579bba.
- linux+kernel: update to 6.10.10-rc1
- linux-kernel: update to 6.10.10-rc1
    - Bye mips64r6el.
    - Patch due diligence not done yet... Wanna sleep for now.
    - Track patches at https://github.com/AOSC-Tracking/linux @ aosc/v6.10.10-rc1, current HEAD is 89ccd25504a2dec38cd82833c7cb005a56579bba.

Package(s) Affected
-------------------

- kernel-tools: 6.10.10-0.1
- linux+kernel: 3:6.10.10-0.1
- linux-kernel-${__VER}: 1:6.10.10-0.1

Security Update?
----------------

No

Build Order
-----------

```
#buildit linux-kernel linux+kernel kernel-tools
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by KexyBiscuit** [comment]
Smoke testing passed on RedmiBook 16 (锐龙版).
图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on ROG Ally (2023).
图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 VMware VM.

- Product: VMware® Workstation 17 Pro
- Version: 17.6.0 build-24238078
- Host OS version: Windows 11 Enterprise, 64-bit (Build 27695.1000) 10.0.27695
- Accelerate 3D graphics: on
- Firmware type: UEFI
- Host VBS Mode: on
image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on AMD64 generation 2, AMD64 generation 1 and Armv8-A generation 2 Hyper-V VMs.

image
image
image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on ProArt B550-CREATOR.

图片

**Review by stdmnpkg — APPROVED** [review]
works on my loongarch64 machine

image

**Comment by KexyBiscuit** [comment]
Smoke testing passed on 战神Z8-KP7S2.

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Latitude D630.

图片

**Comment by KexyBiscuit** [comment]
Smoke testing passed on Surface Pro (5th Gen).

图片

**Pull request merged**
