### PR TITLE
crow-translate: new, 2.8.4

### PR DESCRIPTION
**Pull request by WhiredPlanck**
Topic Description
-----------------

Add `crow-translate`, A simple and lightweight translator that allows you to translate and speak text using Google, Yandex and Bing. 

Package(s) Affected
-------------------

- `crow-translate`

Security Update?
----------------

No

Build Order
-----------

`tesseract` ( #3350 ) -> `crow-translate`

Architectural Progress
----------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`
    

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

### CODE REVIEW

**Comment by WhiredPlanck** [comment]
At this time, run this software in terminal

```bash
$ crow 
```

will crash with error " _!strcmp(locale, "C"):Error:Assert failed:in file baseapi.cpp, line 209_ ". 

Following the [crow-tranlate#197](https://github.com/crow-translate/crow-translate/issues/197#issuecomment-718863619) or [crow-translate#234](https://github.com/crow-translate/crow-translate/issues/234#issuecomment-759281002) could still not fix the problem, and failed to start up the software with following error imformation: 

```text
No protocol specified
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
```

**UPDATE**: Use ``` $ LANG="C" crow ``` can temperately fix staring up failure.

**Comment by WhiredPlanck** [comment]
> **UPDATE**: Use `$ LANG="C" crow` can temperately fix staring up failure.

`tesseract` needs to upgrade.

**Comment by eatradish** [comment]
@WhiredPlanck 我們是不是可以自己寫個補丁修一下（

**Comment by WhiredPlanck** [comment]
LGTM (amd64)
图片

**Review by liushuyu — APPROVED** [review]

**Pull request merged**
