### PR TITLE
OpenJDK Survey (Sept. 2024)

### PR DESCRIPTION
**Pull request by xtexx**
Topic Description
-----------------

- openjfx-11: fix prepare
- openjfx-8: fix prepare
- openjdk+latest: update to 23
- openjfx+latest: new, 23
- openjfx: make openjfx transitional
- openjfx-21: new from openjfx
- openjfx-11: fix prepare
- openjfx-8: fix prepare
- openjdk-8: fix alternatives script
- openjdk-23: show final postinst script

... and 74 more commits

Package(s) Affected
-------------------

- openjdk: 4:21
- openjdk+latest: 23
- openjdk-11: 3:11.0.24+ga
- openjdk-17: 3:17.0.12+ga-1
- openjdk-21: 3:21.0.4+ga-1
- openjdk-22: 3:22.0.2+ga-1
- openjdk-23: 3:23+ga-1
- openjdk-8: 3:8u422+ga-2
- openjdk-common: 1
- openjfx: 1:21
- openjfx+latest: 23
- openjfx-11: 11.0.20+1-1
- openjfx-17: 17.0.13+0
- openjfx-21: 21.0.5+0
- openjfx-22: 22.0.2+ga
- openjfx-23: 23+ga
- openjfx-8: 8u202+ga-12

Security Update?
----------------

No

Build Order
-----------

```
#buildit openjdk-common openjdk-8 openjfx-8 openjdk-11 openjfx-11 openjdk-17 openjfx-17 openjdk-21:+stage2 openjdk-21 openjfx-21 openjdk-22 openjfx-22 openjdk-23 openjfx-23 openjdk openjdk+latest openjfx openjfx+latest
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by xtexx** [comment]
```
# OPENJDK SURVEY (SEPT. 2024)
# TESTING BUILD
/build openjdk-survey openjdk-common,openjdk-8:+stage2,openjdk-8,openjfx-8 amd64,arm64,loongarch64,loongson3,ppc64el
/build openjdk-survey openjdk-common,openjdk-11,openjfx-11 amd64,arm64,ppc64el,riscv64
/build openjdk-survey openjdk-common,openjdk-17:+stage2,openjdk-17,openjfx-17 amd64,arm64,loongarch64,loongson3,ppc64el,riscv64
/build openjdk-survey openjdk-common,openjdk-21:+stage2,openjdk-21,openjfx-21,openjdk,openjfx,openjdk-22:+stage2,openjdk-22,openjfx-22,openjdk-23:+stage2,openjdk-23,openjfx-23,openjdk+latest,openjfx+latest amd64,arm64,loongarch64,loongson3,ppc64el,riscv64

# OPENPR
/openpr OpenJDK Survey (Sept. 2024);openjdk-survey;openjdk-common,openjdk-8,openjfx-8,openjdk-11,openjfx-11,openjdk-17,openjfx-17,openjdk-21:+stage2,openjdk-21,openjfx-21,openjdk-22,openjfx-22,openjdk-23,openjfx-23,openjdk,openjdk+latest,openjfx,openjfx+latest;survey,upgrade,new-packages,manual-build

# STABLE BUILD
/build stable openjdk-common amd64
/build stable openjdk-8:+stage2,openjdk-8,openjfx-8 amd64,arm64,loongarch64,loongson3,ppc64el
/build stable openjdk-11,openjfx-11 amd64,arm64,ppc64el,riscv64
/build stable openjdk-17:+stage2,openjdk-17,openjfx-17 amd64,arm64,loongarch64,loongson3,ppc64el,riscv64
/build stable openjdk-21:+stage2,openjdk-21,openjfx-21,openjdk,openjfx amd64,arm64,loongarch64,loongson3,ppc64el,riscv64
#   after 21 is built
/build stable openjdk-22:+stage2,openjdk-22,openjfx-22 amd64,arm64,loongarch64,loongson3,ppc64el,riscv64
#   after 22 is built
/build stable openjdk-23:+stage2,openjdk-23,openjfx-23,openjdk+latest,openjfx+latest amd64,arm64,loongarch64,loongson3,ppc64el,riscv64

# OPT-IN
oma topics --opt-in openjdk-survey
```

**Comment by xtexx** [comment]
Current pipelines:
- https://buildit.aosc.io/pipelines/10502
- https://buildit.aosc.io/pipelines/10513
- https://buildit.aosc.io/pipelines/10509
- https://buildit.aosc.io/pipelines/10510

**Comment by MingcongBai** [comment]
LGTM. Upgrades went smoothly.

**Comment by MingcongBai** [comment]
> ```
> # OPENJDK SURVEY (SEPT. 2024)
> # TESTING BUILD
> /build openjdk-survey openjdk-common,openjdk-8:+stage2,openjdk-8,openjfx-8 amd64,arm64,loongarch64,loongson3,ppc64el
> /build openjdk-survey openjdk-common,openjdk-11,openjfx-11 amd64,arm64,ppc64el,riscv64
> /build openjdk-survey openjdk-common,openjdk-17:+stage2,openjdk-17,openjfx-17 amd64,arm64,loongarch64,loongson3,ppc64el,riscv64
> /build openjdk-survey openjdk-common,openjdk-21:+stage2,openjdk-21,openjfx-21,openjdk,openjfx,openjdk-22:+stage2,openjdk-22,openjfx-22,openjdk-23:+stage2,openjdk-23,openjfx-23,openjdk+latest,openjfx+latest amd64,arm64,loongarch64,loongson3,ppc64el,riscv64
> 
> # OPENPR
> /openpr OpenJDK Survey (Sept. 2024);openjdk-survey;openjdk-common,openjdk-8,openjfx-8,openjdk-11,openjfx-11,openjdk-17,openjfx-17,openjdk-21:+stage2,openjdk-21,openjfx-21,openjdk-22,openjfx-22,openjdk-23,openjfx-23,openjdk,openjdk+latest,openjfx,openjfx+latest;survey,upgrade,new-packages,manual-build
> 
> # STABLE BUILD
> /build stable openjdk-common amd64
> /build stable openjdk-8:+stage2,openjdk-8,openjfx-8 amd64,arm64,loongarch64,loongson3,ppc64el
> /build stable openjdk-11,openjfx-11 amd64,arm64,ppc64el,riscv64
> /build stable openjdk-17:+stage2,openjdk-17,openjfx-17 amd64,arm64,loongarch64,loongson3,ppc64el,riscv64
> /build stable openjdk-21:+stage2,openjdk-21,openjfx-21,openjdk,openjfx amd64,arm64,loongarch64,loongson3,ppc64el,riscv64
> #   after 21 is built
> /build stable openjdk-22:+stage2,openjdk-22,openjfx-22 amd64,arm64,loongarch64,loongson3,ppc64el,riscv64
> #   after 22 is built
> /build stable openjdk-23:+stage2,openjdk-23,openjfx-23,openjdk+latest,openjfx+latest amd64,arm64,loongarch64,loongson3,ppc64el,riscv64
> 
> # OPT-IN
> oma topics --opt-in openjdk-survey
> ```

This routine has been unified as one and should build for all architectures.

**Comment by OriginCode** [comment]
LGTM on amd64
圖片

**Review by OriginCode — APPROVED** [review]

**Pull request merged**
