### PR TITLE
{openjdk,openjfx}{,-17,-8,-11}: updates

### PR DESCRIPTION
**Pull request by xtexx**
Topic Description
-----------------

- openjfx: update to 21.0.5+0
- openjdk: update to 21.0.4-ga
- openjfx-17: new, 17.0.13+0
    - new, 17.0.9+3 (derive from openjfx)
    - update to 17.0.13+0
- openjdk-17: new, 17.0.12+ga
- openjdk-8: update to 8u422+ga
    - update to 8u422+ga
    - add loongson3 patch
    - add stage2 build script
    - remove webkit from amd64 due to build failures
- openjfx: use openjfx-common
- openjfx-11: use openjfx-common
- openjfx-8: use openjfx-common
- openjfx-common: new, 1
- openjfx-11: rebase patches

... and 1 more commits

Package(s) Affected
-------------------

- openjdk: 3:21.0.4-ga
- openjdk-17: 3:17.0.12+ga
- openjdk-8: 3:8u422+ga
- openjfx: 21.0.5+0
- openjfx-11: 11.0.20+1-1
- openjfx-17: 17.0.13+0
- openjfx-8: 8u202+ga-12
- openjfx-common: 1

Security Update?
----------------

No

Build Order
-----------

```
#buildit openjfx-common openjdk-8:+stage2 openjdk-8 openjfx-8 openjfx-11 openjdk-17:+stage2 openjdk-17 openjfx-17 openjdk:+stage2 openjdk openjfx
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by xtexChooser** [comment]
dickens report (Fri, 09 Aug 2024 18:10:54 +0800):
https://paste.aosc.io/paste/aOVIIvdEgZ2naatqaCArHA

**Comment by xtexx** [comment]
```
# riscv64 is not supported by openjdk 8

# TESTING BUILD
/build openjdk-21.0.5 openjdk-8:+stage2,openjdk-8,openjfx-common,openjfx-8 amd64,arm64,ppc64el,loongson3,loongarch64
/build openjdk-21.0.5 openjfx-common,openjfx-11 amd64,arm64,ppc64el,riscv64
/build openjdk-21.0.5 openjdk-17:+stage2,openjdk-17,openjfx-common,openjfx-17 amd64,arm64,ppc64el,loongson3,loongarch64,riscv64
/build openjdk-21.0.5 openjdk:+stage2,openjdk,openjfx-common,openjfx amd64,arm64,ppc64el,loongson3,loongarch64,riscv64

# STABLE BUILD
/build openjdk-21.0.5 openjfx-common amd64
# wait for openjfx-common, then parallel run
/build openjdk-21.0.5 openjdk-8:+stage2,openjdk-8,openjfx-8 amd64,arm64,ppc64el,loongson3,loongarch64
/build openjdk-21.0.5 openjfx-11 amd64,arm64,ppc64el,riscv64
/build openjdk-21.0.5 openjdk-17:+stage2,openjdk-17,openjfx-17 amd64,arm64,ppc64el,loongson3,loongarch64,riscv64
/build openjdk-21.0.5 openjdk:+stage2,openjdk,openjfx amd64,arm64,ppc64el,loongson3,loongarch64,riscv64
```

**Comment by xtexx** [comment]
Current BuildIt! pipelines: 9038 - 9041
- https://buildit.aosc.io/pipelines/9038 (OpenJDK/OpenJFX 8)
- https://buildit.aosc.io/pipelines/9039 (OpenJFX 11)
- https://buildit.aosc.io/pipelines/9040 (OpenJDK/OpenJFX 17)
- https://buildit.aosc.io/pipelines/9041 (OpenJDK/OpenJFX 21)

**Comment by xtexx** [comment]
LGTM on amd64
image

**Comment by xtexx** [comment]
Superseded by #7622

**Pull request closed without merging**
