### PR TITLE
template: update PULL_REQUEST_TEMPLATE

### PR DESCRIPTION
**Pull request by MingcongBai**
- Do not include checkboxes in Yes/No questions. This could be confusing as there will always be a task "unfinished."
- Do not enable optenv32 by default.
- Include a post-merge stub.

### CODE REVIEW

**Comment by MingcongBai** [comment]
Preview
======



Topic Description
-----------------



Package(s) Affected
-------------------



Security Update?
----------------










Architectural Progress
----------------------



- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`
    





Secondary Architectural Progress
--------------------------------



Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------



- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`






Post-Merge Secondary Architectural Progress
-------------------------------------------



Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`

**Comment by szclsya** [comment]
We may want include build order in the template?

**Review by neruthes — APPROVED** [review]

**Comment by MingcongBai** [comment]
> We may want include build order in the template?

Good idea... I will add this.

**Comment by szclsya** [comment]
> > We may want include build order in the template?
> 
> Good idea... I will add this.

I think we can set that to `Arbitrary` in the default template to reduce keyboard works.

**Comment by MingcongBai** [comment]
@szclsya Updated again in the branch. I have also updated the preview comment above.

**Comment by szclsya** [comment]
LGTM

**Review by Fearyncess — APPROVED** [review]

**Pull request merged**
