### PR TITLE
linux-kernel: update to 6.10.3

### PR DESCRIPTION
**Pull request by KexyBiscuit**
Topic Description
-----------------

- kernel-tools: update to 6.10.3
- linux+kernel: update to 6.10.3
- linux-kernel: update to 6.10.3
    - (loongarch64) Introduce old-world boot support.
    - Refreshed every patch that could be traced.
    - For now, only the following patches are LoongArch64 specific.
    - [LOONGARCH64] drivers/firmware: Move sysfb_init() from device_initcall to fs_initcall
    - [LOONGARCH64] drm/xe: fix build on non-4K kernels
    - [LOONGARCH64] drm/radeon: Workaround radeon driver bug for Loongson
    - [LOONGARCH64] drm/radeon: Call mmiowb() at the end of radeon_ring_commit()
    - Most patches are now properly credited.
    - Track patches at https://github.com/AOSC-Tracking/linux/commits/aosc/v6.10.3.

Package(s) Affected
-------------------

- kernel-tools: 6.10.3
- linux+kernel: 3:6.10.3
- linux-kernel-6.10.3: 1:6.10.3

Security Update?
----------------

No

Build Order
-----------

```
#buildit linux-kernel linux+kernel kernel-tools
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by KexyBiscuit** [comment]
Boots on AMD64 and AA64 Hyper-V VMs.
image
image

**Comment by Fearyncess** [comment]
图片

la64 test passed, ntfs3 works well w/o kernel panic

**Comment by MingcongBai** [comment]
Introduced old-world compatibility patch for LoongArch. LoongArch users are encouraged to retest.

**Comment by KexyBiscuit** [comment]
Boots on AMD64 Hyper-V VM.
image

**Comment by KexyBiscuit** [comment]
Boots on AArch64 Hyper-V VM.
image

**Comment by MingcongBai** [comment]
Alive and well here on my Lenovo Kaitian M540z (LoongArch, old-world):

图片

**Review by MingcongBai — APPROVED** [review]

**Pull request merged**
