### PR TITLE
nuget: update to 4.9.3

### PR DESCRIPTION
**Pull request by KexyBiscuit**
See also: [NuGet 4.9 Release Notes](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-4.9-rtm)

### CODE REVIEW

**Comment by MingcongBai** [comment]
Not sure if this will build. Would you mind testing this out?

I can also test it if you want.

**Comment by KexyBiscuit** [comment]
I'll try.

**Comment by KexyBiscuit** [comment]
It now builds.
How is this PR being ready with question label?

**Comment by MingcongBai** [comment]
> It now builds.

Cool beans.

> How is this PR being ready with question label?

I marked it there when we weren't sure if it'd build. Removing now.

I will also merge this PR, thanks for your contribution.

If you are interested, please contact me via jeffbai at aosc dot io or on Telegram (if you still use it) - I will provide you with information for an @aosc.io email address and a personal page on our community portal.

This offer is provided for all contributors.

**Comment by eatradish** [comment]
@KexyBiscuit don't add `PKGVER` to defines....

**Comment by MingcongBai** [comment]
Well @KexyBiscuit didn't need to, and it's in `spec` now. I will clean that up in a couple minutes.

**Pull request merged**
