### PR TITLE
frp: update to 0.59.0

### PR DESCRIPTION
**Pull request by SkyBird233**
Topic Description
-----------------

- frp: update to 0.59.0

Package(s) Affected
-------------------

- frp: 0.59.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit frp
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by MingcongBai** [comment]
Both services fails out of the box with error code 1.

**Review by MingcongBai — CHANGES_REQUESTED** [review]
Both services fail out of the box with error code 1. Maybe I didn't understand how to use this right?

**Comment by SkyBird233** [comment]
> Both services fail out of the box with error code 1. Maybe I didn't understand how to use this right?

frp changed default configuration format from ini to toml, but there's a patch reverting upstream change "remove systemd files" using ini. (44802444e2dc00d0c488d414df15a3a2b381947e)

Should we stop providing systemd services of frp or update them?

**Comment by MingcongBai** [comment]
> > Both services fail out of the box with error code 1. Maybe I didn't understand how to use this right?
> 
> frp changed default configuration format from ini to toml, but there's a patch reverting upstream change "remove systemd files" using ini. ([4480244](https://github.com/AOSC-Dev/aosc-os-abbs/commit/44802444e2dc00d0c488d414df15a3a2b381947e))
> 
> Should we stop providing systemd services of frp or update them?

Please update the units as the user would be utterly confused if we just removed it randomly.

**Comment by prcups** [comment]
I have successfully create a connection
Screenshot_20240719_100349

**Comment by KexyBiscuit** [comment]
> I have successfully create a connection Screenshot_20240719_100349

Are the systemd services working now?

**Review by SkyBird233 — COMMENTED** [review]
I don't think editing the patch directly is a good idea. Using overrides may be a better choice?
Apologies for my unavailability these days due to a busy schedule.

**Comment by MingcongBai** [comment]
> I don't think editing the patch directly is a good idea. Using overrides may be a better choice? Apologies for my unavailability these days due to a busy schedule.

@prcups Yes, please re-generate the patch and maintain it in AOSC-Tracking if needed.

**Comment by prcups** [comment]
@SkyBird233 @MingcongBai Have changed to overrides.

**Review by MingcongBai — APPROVED** [review]
systemd units tested good.

**Pull request merged**
