### PR TITLE
[Early Stable] chromium: update to 128.0.6613.36

### PR DESCRIPTION
**Pull request by KexyBiscuit**
Topic Description
-----------------

- chromium: update to 128.0.6613.36
    - Track patches at https://dev.azure.com/AOSC-Tracking/_git/chromium @ aosc/v128.0.6613.36.

Package(s) Affected
-------------------

- chromium: 128.0.6613.36

Security Update?
----------------

No

Build Order
-----------

```
#buildit chromium
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [ ] LoongArch 64-bit `loongarch64`

### CODE REVIEW

**Comment by KexyBiscuit** [comment]
FTBFS on LA64.

```
FAILED: chrome 
(cmdline)
ld.lld: error: undefined symbol: SkOpts::Init_lasx()
>>> referenced by SkOpts.cpp:65 (../../third_party/skia/src/core/SkOpts.cpp:65)
>>>               obj/skia/skia_core_and_effects/chrome.lto.SkGraphics.o:(SkGraphics::Init())
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jiegec** [comment]
> FTBFS on LA64.
> 
> ```
> FAILED: chrome 
> (cmdline)
> ld.lld: error: undefined symbol: SkOpts::Init_lasx()
> >>> referenced by SkOpts.cpp:65 (../../third_party/skia/src/core/SkOpts.cpp:65)
> >>>               obj/skia/skia_core_and_effects/chrome.lto.SkGraphics.o:(SkGraphics::Init())
> clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> ```

See https://github.com/AOSC-Dev/chromium-loongarch64/commit/3a8717fb48b4b71c8f288c2a15568570b1b03b94

**Comment by MingcongBai** [comment]
Closing for another attempt later.

**Comment by jiegec** [comment]
Plans for chromium 131? Patches have been tested at https://github.com/AOSC-Dev/chromium-loongarch64.

**Pull request closed without merging**
