### PR TITLE
Utilities (util-base) Survey 20221214

### PR DESCRIPTION
**Pull request by MingcongBai**
Topic Description
-----------------

This topic surveys updates in `util-base`, improving scripting quality where applicable.

Package(s) Affected
-------------------

- [x] `lapack` v3.9.0-2
- [x] `coreutils` v9.1
- [x] `dos2unix` v7.4.3
- [x] `elfutils` v0.188
- [x] `file` v5.43
- [x] `findutils` v4.9.0
- [x] `gawk` v5.2.1
- [x] `grep` v3.8
- [x] `hdparm` v9.65
- [x] `htop` v3.2.1
- [x] `kbd` v2.5.1
- [x] `kmod` v30
- [x] `less` v608
- [x] `libarchive` v3.6.2
- [x] `lrzip` v0.651
- [x] `lshw` v02.19.2
- [x] `lsof` v4.96.4
- [x] `lz4` v1.9.4
- [x] `lzip` v1.23
- [x] `man-db` v2.11.1
- [x] `man-pages` v6.01+posix2017-a
- [x] `nano` v7.0+nanorc20221128
- [x] `neofetch` v7.3.3
- [x] `nethogs` v0.8.7
- [x] `newt` v0.52.23
- [x] `p7zip` v17.04
- [x] `pciutils` v3.9.0
- [x] `procps` v4.0.2
- [x] `progress` v0.16
- [x] `psmisc` v23.6
- [x] `pv` v1.6.20
- [x] `screen` v4.9.0
- [x] `sdparm` v1.12
- [x] `sed` v4.9
- [x] `texinfo` v7.0.1
- [x] `tmux` v3.3a
- [x] `tree` v2.0.4
- [x] `unrar` v6.2.2
- [x] `usbutils` v015
- [x] `util-linux` v2.38.1
- [x] `xz` v5.4.0

Security Update?
----------------

No

Build Order
-----------

```
lapack xz kmod nano man-pages coreutils libarchive elfutils file findutils gawk texinfo grep kbd less lsof man-db procps psmisc screen sed tmux htop newt nethogs dos2unix hdparm lrzip lshw lz4 lzip neofetch p7zip pciutils progress pv sdparm tree unrar usbutils libeconf util-linux
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

Update(s) Uploaded to Stable
----------------------------

**Primary Architectures**

- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

**Secondary Architectures**

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by OriginCode** [comment]
圖片

**Comment by OriginCode** [comment]
圖片

**Comment by OriginCode** [comment]
圖片

**Comment by OriginCode** [comment]
`/etc/profile.d/mcfly.bash` needs an update.
圖片

**Review by Cyanoxygen — DISMISSED** [review]

**Review by Cyanoxygen — APPROVED** [review]

**Pull request merged**
