### PR TITLE
boinc: update to 7.16.16

### PR DESCRIPTION
**Pull request by OriginCode**
Topic Description
-----------------

Update boinc to 7.16.16, fix boincmgr library dep.

Package(s) Affected
-------------------

boinc

Security Update?
----------------

No

Architectural Progress
----------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

### CODE REVIEW

**Review by MingcongBai — APPROVED** [review]

**Comment by OriginCode** [comment]
Running with warnings.
image

**Comment by MingcongBai** [comment]
This shouldn't happen though... There is no ABI to mismatch, since you are using that exact library to build, then to run BOINC.

**Comment by OriginCode** [comment]
LGTM, no warning emitted.
image

**Comment by MingcongBai** [comment]
Ship it.

**Pull request merged**
