### PR TITLE
linux-kernel-retro: (i486) enable CONFIG_SATA_SIL

### PR DESCRIPTION
**Pull request by arkadijs**
Hi, on Retro this enables support for very common Silicon Image SiI 3112 based 2-port SATA PCI cards. Please enable.

For me, the onboard Via SATA controller of Athlon XP board is physically broken. There is a high chance for people wanting to add SATA drives to their IDE systems to end up with a SiI PCI controller.

`CONFIG_SATA_SIL` depends on `SATA_HOST` and `PCI` only, so there is no additional options to configure.

(reopened on `retro` branch)

### CODE REVIEW

**Review by MingcongBai — APPROVED** [review]

**Comment by MingcongBai** [comment]
Thanks!

**Comment by MingcongBai** [comment]
@arkadijs As a perk, we offer all new contributors membership in our organisation and an AOSC e-mail account. I have sent you an invitation.

Please let me know if you would like to register an account. If so, I would need the following:

- Your preferred username (the part before @aosc.io).
- Full name (or displayed name) on that e-mail account.
- E-mail address for password recovery.

Please send these details to < jeffbai at aosc dot io >.

Thank you again for your contribution.

**Comment by MingcongBai** [comment]
An update has been made available, you should be able to update your kernel shortly (5.10.204).

**Comment by arkadijs** [comment]
Thank you, I've accepted the GitHub invitation and looking forward to engage with AOSC OS project as time permits. No need for the aosc.io email account for now.

**Pull request merged**
