### PR TITLE
linux-kernel (Linux Kernel): update to 6.10.7

### PR DESCRIPTION
**Pull request by MingcongBai**
Topic Description
-----------------

- kernel-tools: update to 6.10.7
- linux+kernel: update to 6.10.7
- linux-kernel: update to 6.10.7
    - Fix H.264 hardware decoding on Radeon 520 (and possibly other GCN 1.0 and
    2.0 cards). [^1] [^2] [^3]
    - Fix VMGFX (VMSVGA) on VirtualBox and VMware virtual machines without 3D
    acceleration enabled (desktop freezes and boot failures). [^4] [^5]
    - Refresh patches at AOSC-Tracking/linux @ aosc/v6.10.7,
    HEAD: 3ba5dc440300ab47a8564f4a3a391191b9b2f2ef.
    - Use __VER to remove hard-coded versioning in autobuild/defines.
    - Drop upstream-removed CONFIG_KALLSYMS_BASE_RELATIVE option.
    [^1]: https://gitlab.freedesktop.org/drm/amd/-/issues/3599
    [^2]: https://gitlab.freedesktop.org/drm/amd/-/issues/3501
    [^3]: https://github.com/torvalds/linux/commit/f3572db3c049b4d32bb5ba77ad5305616c44c7c1
    [^4]: https://bbs.archlinux.org/viewtopic.php?id=298491
    [^5]: https://lore.kernel.org/lkml/20240819194911.7999bec1@riri/T/

Package(s) Affected
-------------------

- kernel-tools: 6.10.7
- linux+kernel: 3:6.10.7
- linux-kernel: 1:6.10.7

Security Update?
----------------

No

Build Order
-----------

```
#buildit linux-kernel linux+kernel kernel-tools
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by MingcongBai** [comment]
Includes a revert for a change in 6.10.4 which broke H.264 hardware decoding on GCN 1.0/2.0, but may cause green blocks for AV1 hardware decoding on RDNA. Tests pending.

References:

- https://gitlab.freedesktop.org/drm/amd/-/issues/3599
- https://gitlab.freedesktop.org/drm/amd/-/issues/3510
- https://gitlab.freedesktop.org/drm/amd/-/issues/3501
- https://github.com/torvalds/linux/commit/f3572db3c049b4d32bb5ba77ad5305616c44c7c1

**Comment by Cyanoxygen** [comment]
# Testing

Virtualbox
----------

Previously, 3D acceleration can not be enabled due to `vmwgfx` crashing. This update has fixed the problem, now Virtualbox can enable 3D acceleration:

image

VMware
--------

Since 6.10.4 there is an issue with 3D-acceleration-disabled VMSVGA graphics card, resulting an black screen. This is fixed in the update.

image

We have to use the modesetting driver as `vmwgfx` already supports KMS, and X11 lags a lot if `xf86-video-vmware` is used. But it lacks VSync if 3D acceleration is enabled, resulting in blazing fast animations and screen tearing.

**Review by Cyanoxygen — APPROVED** [review]

**Comment by MingcongBai** [comment]
> Includes a revert for a change in 6.10.4 which broke H.264 hardware decoding on GCN 1.0/2.0, but may cause green blocks for AV1 hardware decoding on RDNA. Tests pending.
> 
> References:
> 
>     * https://gitlab.freedesktop.org/drm/amd/-/issues/3599
> 
>     * https://gitlab.freedesktop.org/drm/amd/-/issues/3510
> 
>     * https://gitlab.freedesktop.org/drm/amd/-/issues/3501
> 
>     * [torvalds/linux@f3572db](https://github.com/torvalds/linux/commit/f3572db3c049b4d32bb5ba77ad5305616c44c7c1)

Unfortunately, RDNA4 is still broken with the revert (8845H + 780M) - I will keep the fix and mark Radeon 520 as broken for now:

图片

**Comment by MingcongBai** [comment]
> > Includes a revert for a change in 6.10.4 which broke H.264 hardware decoding on GCN 1.0/2.0, but may cause green blocks for AV1 hardware decoding on RDNA. Tests pending.
> > References:
> > ```
> > * https://gitlab.freedesktop.org/drm/amd/-/issues/3599
> > 
> > * https://gitlab.freedesktop.org/drm/amd/-/issues/3510
> > 
> > * https://gitlab.freedesktop.org/drm/amd/-/issues/3501
> > 
> > * [torvalds/linux@f3572db](https://github.com/torvalds/linux/commit/f3572db3c049b4d32bb5ba77ad5305616c44c7c1)
> > ```
> 
> Unfortunately, RDNA4 is still broken with the revert (8845H + 780M) - I will keep the fix and mark Radeon 520 as broken for now:
> 
> 图片

Wait, this is 6.10.6 (my mistake) - then WTF did that patch fix...?

**Comment by MingcongBai** [comment]
> > > Includes a revert for a change in 6.10.4 which broke H.264 hardware decoding on GCN 1.0/2.0, but may cause green blocks for AV1 hardware decoding on RDNA. Tests pending.
> > > References:
> > > ```
> > > * https://gitlab.freedesktop.org/drm/amd/-/issues/3599
> > > 
> > > * https://gitlab.freedesktop.org/drm/amd/-/issues/3510
> > > 
> > > * https://gitlab.freedesktop.org/drm/amd/-/issues/3501
> > > 
> > > * [torvalds/linux@f3572db](https://github.com/torvalds/linux/commit/f3572db3c049b4d32bb5ba77ad5305616c44c7c1)
> > > ```
> > 
> > 
> > Unfortunately, RDNA4 is still broken with the revert (8845H + 780M) - I will keep the fix and mark Radeon 520 as broken for now:
> > 图片
> 
> Wait, this is 6.10.6 (my mistake) - then WTF did that patch fix...?

Yeah I'm not sure if that patch had fixed anything really... AV1 is still broken on 6.10.7, with that patch reverted.

图片

Well, Radeon 520 (GCN 1.0) is now tested good, so I think we can take that as a win for now.

**Pull request merged**
