### PR TITLE
wine: update to 6.3

### PR DESCRIPTION
**Pull request by Fearyncess**
Topic Description
-----------------
Update `wine` to the version 6.3

Package(s) Affected
-------------------
- wine

Security Update?
----------------
No

Architectural Progress
----------------------
- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

----

Post-Merge Architectural Progress
---------------------------------
- [ ] AMD64 `amd64`   
- [ ] AArch64 `arm64`

### CODE REVIEW

**Comment by Fearyncess** [comment]
图片
Wine 6.3,  running WeChat on AMD64

**Review by Icenowy — APPROVED** [review]
LGTM, but not tested yet.

**Comment by Icenowy** [comment]
Trying to test on arm64.

Winecfg runs, but I am struggling acquiring a Windows for ARM64 binary.

**Comment by MingcongBai** [comment]
@Icenowy That’s an improvement from 6.1. It didn’t even launch on AArch64.

**Comment by Fearyncess** [comment]
> Trying to test on arm64.
> 
> Winecfg runs, but I am struggling acquiring a Windows for ARM64 binary.

7zip has a ARM64 build for 20.01.
it may be use for the test?

**Comment by Icenowy** [comment]
Well the dialog that says wine prefix being updated is still preserved here, even after winecfg exits.

`C:\windows\system32\rundll32.exe setupapi,InstallHinfSection DefaultInstall 128 \\?\Z:\usr\bin\..\share\wine\wine.inf` is using 100% (single core) of a CPU.

Looks like a CPU power issue (device is Pinebook Pro).

And when running new program, the newly invoked wine process will wait for the initial configuration to be done, and only get really executed after it times out.

7-zip ARM64 installer runs, now trying to launch 7zFM.

**Pull request merged**
