### PR TITLE
qemu: update to 9.2.0

### PR DESCRIPTION
**Pull request by jiegec**
Topic Description
-----------------

- qemu: update to 9.2.0
    Co-authored-by: Chen (@jiegec) <c@jia.je>

Package(s) Affected
-------------------

- qemu: 9.2.0
- qemu-aarch64-static: 9.2.0
- qemu-alpha-static: 9.2.0
- qemu-arm-static: 9.2.0
- qemu-armeb-static: 9.2.0
- qemu-cris-static: 9.2.0
- qemu-guest-agent: 9.2.0
- qemu-i386-static: 9.2.0
- qemu-loongarch64-static: 9.2.0
- qemu-m68k-static: 9.2.0
- qemu-microblaze-static: 9.2.0
- qemu-microblazeel-static: 9.2.0
- qemu-mips-static: 9.2.0
- qemu-mips64-static: 9.2.0
- qemu-mips64el-static: 9.2.0
- qemu-mipsel-static: 9.2.0
- qemu-mipsn32-static: 9.2.0
- qemu-mipsn32el-static: 9.2.0
- qemu-nios2-static: 9.2.0
- qemu-or32-static: 9.2.0
- qemu-ppc-static: 9.2.0
- qemu-ppc64-static: 9.2.0
- qemu-ppc64le-static: 9.2.0
- qemu-riscv32-static: 9.2.0
- qemu-riscv64-static: 9.2.0
- qemu-s390x-static: 9.2.0
- qemu-sh4-static: 9.2.0
- qemu-sh4eb-static: 9.2.0
- qemu-sparc-static: 9.2.0
- qemu-sparc32plus-static: 9.2.0
- qemu-sparc64-static: 9.2.0
- qemu-user-static: 9.2.0
- qemu-x86-64-static: 9.2.0

Security Update?
----------------

No

Build Order
-----------

```
#buildit qemu
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by jiegec** [comment]
loongson3 patch partially upstreamed: https://github.com/qemu/qemu/commit/e922abf5c0e40eb451434c4121b730c8a19d80d4, @chenx97 please check

**Comment by MingcongBai** [comment]
> loongson3 patch partially upstreamed: [qemu/qemu@e922abf](https://github.com/qemu/qemu/commit/e922abf5c0e40eb451434c4121b730c8a19d80d4), @chenx97 please check

Seems not to be a direct equivalent since it's missing a check for `EF_MIPS_NAN2008` to discern between 3A1000 and 3A4000.

**Comment by chenx97** [comment]
> > loongson3 patch partially upstreamed: [qemu/qemu@e922abf](https://github.com/qemu/qemu/commit/e922abf5c0e40eb451434c4121b730c8a19d80d4), @chenx97 please check
> 
> Seems not to be a direct equivalent since it's missing a check for `EF_MIPS_NAN2008` to discern between 3A1000 and 3A4000.

Our binaries are all 3A1000 so it doesn't really matter.

**Comment by chenx97** [comment]
Also, unlike [P5600](https://github.com/qemu/qemu/blob/ae35f033b874c627d81d51070187fbf55f0bf1a7/target/mips/cpu-defs.c.inc#L461), QEMU's [Loongson-3A4000](https://github.com/qemu/qemu/blob/ae35f033b874c627d81d51070187fbf55f0bf1a7/target/mips/cpu-defs.c.inc#L943) doesn't have nan2008, so the original patch was wrong and assumed QEMU's emulated CPUs to match their real-life counterparts.

**Comment by MingcongBai** [comment]
> Also, unlike [P5600](https://github.com/qemu/qemu/blob/ae35f033b874c627d81d51070187fbf55f0bf1a7/target/mips/cpu-defs.c.inc#L461), QEMU's [Loongson-3A4000](https://github.com/qemu/qemu/blob/ae35f033b874c627d81d51070187fbf55f0bf1a7/target/mips/cpu-defs.c.inc#L943) doesn't have nan2008, so the original patch was wrong and assumed QEMU's emulated CPUs to match their real-life counterparts.

Got it.

**Review by xtexx — APPROVED** [review]
Reviewed-by: ~~~
Tested-by: ~~~ # AMD64

image

**Pull request merged**
