### PR TITLE
atuin: new, 17.2.1

### PR DESCRIPTION
**Pull request by eatradish**
Topic Description
-----------------

- atuin: new, 17.2.1

Package(s) Affected
-------------------

- atuin: 17.2.1

Security Update?
----------------

No

Build Order
-----------

```
#buildit atuin
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`

**Secondary Architectures**

- [ ] Loongson 3 `loongson3`
- [ ] MIPS R6 64-bit (Little Endian) `mips64r6el`
- [ ] PowerPC 64-bit (Little Endian) `ppc64el`
- [ ] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by eatradish** [comment]
@aosc-buildit-bot build amd64

**Comment by eatradish** [comment]
@aosc-buildit-bot build amd64

**Comment by eatradish** [comment]
@aosc-buildit-bot build amd64

**Comment by eatradish** [comment]
@aosc-buildit-bot build

**Comment by eatradish** [comment]
LGTM on AMD64:

图片

**Comment by eatradish** [comment]
@aosc-buildit-bot build

**Review by MingcongBai — APPROVED** [review]

**Comment by eatradish** [comment]
@aosc-buildit-bot build

**Pull request merged**
