### PR TITLE
Mozilla Survey on 20210208

### PR DESCRIPTION
**Pull request by MingcongBai**
Topic Description
-----------------

Survey updates for all Mozilla projects: Firefox, SeaMonkey, Thunderbird.

Package(s) Affected
-------------------

- `firefox` v58.0.2
- `seamonkey` v2.53.6
- `thunderbird` v78.7.1

Security Update?
----------------

Yes.

- Firefox, [MSFA2021-06](https://www.mozilla.org/en-US/security/advisories/mfsa2021-06/).
- Thunderbird, [MSFA2021-02](https://www.mozilla.org/en-US/security/advisories/mfsa2021-02/), [MSFA2021-05](https://www.mozilla.org/en-US/security/advisories/mfsa2021-05/).

Build Order
-----------

Build individually.

Architectural Progress
----------------------

- [x] AMD64 `amd64`   
- [x] AArch64 `arm64`

Secondary Architectural Progress
--------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

----

After the pull request is merged, all package(s) affected must be rebuilt against the `stable` Git tree and environment (only `stable` repository should be enabled in `sources.list`). This section marks the progress above.

Please, make sure the list of architectures below matches the ones above.

Post-Merge Architectural Progress
---------------------------------

- [x] AMD64 `amd64`   
- [ ] AArch64 `arm64`

Post-Merge Secondary Architectural Progress
-------------------------------------------

Architectural progress for "secondary," or experimental ports does not impede on merging of this topic.

- [ ] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`

### CODE REVIEW

**Comment by Cyanoxygen** [comment]
## Testing 

Architecture: AMD64
OS: AOSC OS 8.0.2
DE: Cinnamon, X11

Here's the screenshot showing Thunderbird 78.7.1 running.

image

**Review by Cyanoxygen — APPROVED** [review]

**Comment by Cyanoxygen** [comment]
Firefox 85.0.2:
image

Seamonkey 2.53.6:
image

**Comment by OriginCode** [comment]
LGTM on amd64: (`firefox` and `thunderbird`)
image
image

**Review by OriginCode — APPROVED** [review]

**Comment by MingcongBai** [comment]
@l2dy Please assign an AOSA.

**Comment by l2dy** [comment]
Use AOSA-2021-0006.

**Pull request merged**
